-- ============================================================
-- TABLE: SMXFINANC.SFDEPTARCCON
-- ============================================================
CREATE TABLE SMXFINANC.SFDEPTARCCON (
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOARCHIVODEFINICION DECIMAL(10) NOT NULL,
  CONTENIDOARCHIVO BLOB NOT NULL,
  PRIMARY KEY (CODIGOARCHIVODEFINICION)
);

-- ============================================================
-- TABLE: SMXFINANC.SFDEPTARCDEF
-- ============================================================
CREATE TABLE SMXFINANC.SFDEPTARCDEF (
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOARCHIVODEFINICION DECIMAL(10) NOT NULL,
  NOMBREARCHIVO VARCHAR(128) NOT NULL,
  DESCRIPCIONARCHIVO VARCHAR(200),
  TAMANIOARCHIVO DECIMAL(10,2),
  UNIDADARCHIVO VARCHAR(32),
  ESTADOARCHIVO VARCHAR(32),
  EXTENSIONARCHIVO VARCHAR(32),
  FECHATRANSMISION TIMESTAMP,
  ESTADO VARCHAR(1) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  CODIGOCIERRELOCAL DECIMAL(10),
  PRIMARY KEY (CODIGOARCHIVODEFINICION)
);

-- ============================================================
-- TABLE: SMXFINANC.SFDEPTARQDEP
-- ============================================================
CREATE TABLE SMXFINANC.SFDEPTARQDEP (
  CODIGOARQUEODEPOSITO DECIMAL(10) NOT NULL,
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOAREATRABAJO INTEGER NOT NULL,
  FECHAARQUEO TIMESTAMP NOT NULL,
  CODIGOCATALOGOTIPOESTADOARQUEO INTEGER NOT NULL,
  CODIGOCATALOGOVALORESTADOARQUEO VARCHAR(32) NOT NULL,
  USAMULTIMONEDA VARCHAR(1) NOT NULL,
  CODIGOCATALOGOTIPOMONEDA INTEGER,
  CODIGOCATALOGOVALORMONEDA VARCHAR(32),
  VALORTOTAL DECIMAL(10,2),
  TOTALCOMPROBAR DECIMAL(10,2),
  DIFERENCIA DECIMAL(10,2),
  TASACONVERSION DECIMAL(10,2),
  CODIGOCATALOGOTIPOARQUEO INTEGER,
  CODIGOCATALOGOVALORARQUEO VARCHAR(32),
  VALORTOTALCORREGIDO DECIMAL(10,2),
  DIFERENCIACORREGIDA DECIMAL(10,2),
  VERSION INTEGER NOT NULL,
  ESTADO VARCHAR(1) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  PRIMARY KEY (CODIGOARQUEODEPOSITO)
);

-- ============================================================
-- TABLE: SMXFINANC.SFDEPTARQDEPACTA
-- ============================================================
CREATE TABLE SMXFINANC.SFDEPTARQDEPACTA (
  CODIGOARQUEODEPOSITOACTA DECIMAL(10) NOT NULL,
  CODIGOARQUEODEPOSITO DECIMAL(10) NOT NULL,
  CODIGOCOMPANIA INTEGER NOT NULL,
  USUARIOENTREGA VARCHAR(64),
  USUARIORECIBE VARCHAR(64),
  NOMBREUSUARIOENTREGA VARCHAR(64),
  NOMBREUSUARIORECIBE VARCHAR(64),
  MOTIVO VARCHAR(300),
  OBSERVACION VARCHAR(500),
  MOTIVORECIBE VARCHAR(300),
  OBSERVACIONRECIBE VARCHAR(500),
  VERSION INTEGER NOT NULL,
  ESTADO VARCHAR(1) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  USUARIOENTREGAADMIN VARCHAR(64),
  NOMBREUSUARIOENTREGAADMIN VARCHAR(64),
  PRIMARY KEY (CODIGOARQUEODEPOSITOACTA)
);

-- ============================================================
-- TABLE: SMXFINANC.SFDEPTARQDEPBIT
-- ============================================================
CREATE TABLE SMXFINANC.SFDEPTARQDEPBIT (
  CODIGOARQUEODEPOSITOBITACORA DECIMAL(10) NOT NULL,
  CODIGOARQUEODEPOSITO DECIMAL(10) NOT NULL,
  CODIGOCATALOGOTIPOESTADOARQUEO INTEGER,
  CODIGOCATALOGOVALORESTADOARQUEO VARCHAR(32),
  CODIGOCOMPANIA INTEGER NOT NULL,
  VERSION INTEGER NOT NULL,
  ESTADO VARCHAR(1) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  PRIMARY KEY (CODIGOARQUEODEPOSITOBITACORA)
);

-- ============================================================
-- TABLE: SMXFINANC.SFDEPTARQDEPDET
-- ============================================================
CREATE TABLE SMXFINANC.SFDEPTARQDEPDET (
  CODIGOARQUEODEPOSITODETALLE DECIMAL(10) NOT NULL,
  CODIGOARQUEODEPOSITO DECIMAL(10) NOT NULL,
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOCATALOGOTIPOPAQUETEARQUEODET INTEGER NOT NULL,
  CODIGOCATALOGOVALORPAQUETEARQUEODET VARCHAR(32) NOT NULL,
  CANTIDAD INTEGER,
  CANTIDADFUNDA INTEGER,
  CANTIDADPAQUETE INTEGER,
  CODIGOCATALOGOTIPOMONEDA INTEGER,
  CODIGOCATALOGOVALORMONEDA VARCHAR(32),
  CODIGOCATALOGOTIPODENOMINACION INTEGER,
  CODIGOCATALOGOVALORDENOMINACION VARCHAR(32),
  MULTIPLICADOR DECIMAL(12,2),
  DENOMINACIONPAQUETEMONEDA DECIMAL(12,2),
  CANTIDADPORFUNDA INTEGER,
  CANTIDADPORPAQUETE INTEGER,
  TOTALMULTIPLICADO DECIMAL(10,2),
  TOTALCONVERSION DECIMAL(15,2),
  CANTIDADCORREGIDA DECIMAL(10,2),
  CANTIDADFUNDACORREGIDO DECIMAL(10,2),
  CANTIDADPORFUNDACORREGIDO DECIMAL(10,2),
  CANTIDADPAQUETECORREGIDO DECIMAL(10,2),
  CANTIDADPORPAQUETECORREGIDO DECIMAL(10,2),
  TOTALMULTIPLICADOCORREGIDO DECIMAL(10,2),
  VERSION INTEGER NOT NULL,
  ESTADO VARCHAR(1) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  PRIMARY KEY (CODIGOARQUEODEPOSITODETALLE)
);

-- ============================================================
-- TABLE: SMXFINANC.SFDEPTARQDEPFON
-- ============================================================
CREATE TABLE SMXFINANC.SFDEPTARQDEPFON (
  CODIGOARQUEODEPOSITOFONDO DECIMAL(10) NOT NULL,
  CODIGOARQUEODEPOSITO DECIMAL(10) NOT NULL,
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOCATALOGOTIPOFONDO INTEGER NOT NULL,
  CODIGOCATALOGOVALORPFONDO VARCHAR(32) NOT NULL,
  CODIGOCATALOGOTIPOMONEDA INTEGER,
  CODIGOCATALOGOVALORMONEDA VARCHAR(32),
  CANTIDAD INTEGER,
  VALOR DECIMAL(10,2),
  TOTAL DECIMAL(10,2),
  TOTALCONVERSION DECIMAL(15,2),
  DESCRIPCION VARCHAR(255),
  CANTIDADCORREGIDA DECIMAL(10,2),
  VALORCORREGIDO DECIMAL(10,2),
  TOTALCORREGIDO DECIMAL(10,2),
  VERSION INTEGER NOT NULL,
  ESTADO VARCHAR(1) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  PRIMARY KEY (CODIGOARQUEODEPOSITOFONDO)
);

-- ============================================================
-- TABLE: SMXFINANC.SFDEPTCATVAL
-- ============================================================
CREATE TABLE SMXFINANC.SFDEPTCATVAL (
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOCATALOGOTIPO INTEGER NOT NULL,
  CODIGOCATALOGOVALOR VARCHAR(32) NOT NULL,
  CODIGOCATALOGOTIPOPADRE INTEGER,
  CODIGOCATALOGOVALORPADRE VARCHAR(32),
  NOMBRE VARCHAR(256) NOT NULL,
  NOMBRECORTO VARCHAR(100),
  CODIGOEXTERNO VARCHAR(16),
  MULTIPLICADOR DECIMAL(12,2),
  POSICION INTEGER NOT NULL,
  ESCANTIDAD VARCHAR(1) NOT NULL,
  ESVALOR VARCHAR(1) NOT NULL,
  SUMAVALOR VARCHAR(1) NOT NULL,
  ESVISIBLECANTIDAD VARCHAR(1) NOT NULL,
  ESVISIBLEVALOR VARCHAR(1) NOT NULL,
  ESMETALICO VARCHAR(1) NOT NULL,
  ESCALCULADO VARCHAR(1) NOT NULL,
  REQUIERESERIE VARCHAR(1) NOT NULL,
  MOSTRARTOTAL VARCHAR(1) NOT NULL,
  RELACIONCUADRE VARCHAR(200),
  ESTADO VARCHAR(1) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  ENVIAJDE VARCHAR(1),
  PRIMARY KEY (CODIGOCATALOGOVALOR, CODIGOCATALOGOTIPO)
);

-- ============================================================
-- TABLE: SMXFINANC.SFDEPTCIELOC
-- ============================================================
CREATE TABLE SMXFINANC.SFDEPTCIELOC (
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOCIERRELOCAL DECIMAL(10) NOT NULL,
  CODIGOINTEGRACIONVENTA DECIMAL(10) NOT NULL,
  CODIGOAREATRABAJO INTEGER NOT NULL,
  CODIGOARCHIVODEFINICION DECIMAL(10),
  CODIGOCATALOGOTIPOESTADOCIERRE INTEGER NOT NULL,
  CODIGOCATALOGOVALORESTADOCIERRE VARCHAR(32) NOT NULL,
  FECHACIERRE TIMESTAMP NOT NULL,
  FECHATRANSMISION TIMESTAMP,
  USUARIOTRANSMISION VARCHAR(32),
  USAMULTIMONEDA VARCHAR(1) NOT NULL,
  CODIGOCATALOGOTIPOMONEDA INTEGER,
  CODIGOCATALOGOVALORMONEDA VARCHAR(32),
  ESTADO VARCHAR(1) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  FECHAREABRIR TIMESTAMP,
  USUARIORESPONSABLE VARCHAR(64),
  NOMBREUSUARIORESPONSABLE VARCHAR(64),
  PRIMARY KEY (CODIGOCIERRELOCAL)
);

-- ============================================================
-- TABLE: SMXFINANC.SFDEPTCIELOCCAJ
-- ============================================================
CREATE TABLE SMXFINANC.SFDEPTCIELOCCAJ (
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOCIERRELOCALCAJERO DECIMAL(10) NOT NULL,
  CODIGOCIERRELOCAL DECIMAL(10) NOT NULL,
  CODIGOCAJERO DECIMAL(10),
  USUARIOGENERICO DECIMAL(10),
  DESCUENTONOMINA VARCHAR(1) NOT NULL,
  CODIGOCATALOGOTIPOESTADODESCUENTO INTEGER NOT NULL,
  CODIGOCATALOGOVALORESTADODESCUENTO VARCHAR(32) NOT NULL,
  CODIGOCATALOGOTIPOESTADOREVISION INTEGER NOT NULL,
  CODIGOCATALOGOVALORESTADOREVISION VARCHAR(32) NOT NULL,
  FECHAREVISION TIMESTAMP,
  ESTADO VARCHAR(1) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  ESCUADREMANUAL VARCHAR(1),
  TIENETOTALVENTAS VARCHAR(1),
  REALIZOCUADRE VARCHAR(1),
  DIFERENCIA DECIMAL(12,2),
  PRIMARY KEY (CODIGOCIERRELOCALCAJERO)
);

-- ============================================================
-- TABLE: SMXFINANC.SFDEPTCLOSLOCDOCSUPPORT
-- ============================================================
CREATE TABLE SMXFINANC.SFDEPTCLOSLOCDOCSUPPORT (
  DOCUMENTCODE DECIMAL(10) NOT NULL,
  COMPANYCODE INTEGER NOT NULL,
  CODECATALOGTYPEDOCUMENT INTEGER NOT NULL,
  CODECATALOGVALUEDOCUMENT VARCHAR(32) NOT NULL,
  AREACODE INTEGER,
  EMPLOYEEREFERENCECODE INTEGER NOT NULL,
  TRANSACTIONDATE TIMESTAMP NOT NULL,
  IMAGE VARCHAR(500) NOT NULL,
  STATUS VARCHAR(1) NOT NULL,
  CREATEDBYUSER VARCHAR(50) NOT NULL,
  CREATEDDATE TIMESTAMP NOT NULL,
  LASTMODIFIEDBYUSER VARCHAR(50),
  LASTMODIFIEDDATE TIMESTAMP,
  VERSION INTEGER NOT NULL,
  CREATEDFROMIP VARCHAR(50),
  UPDATEFROMIP VARCHAR(50),
  PRIMARY KEY (DOCUMENTCODE)
);

-- ============================================================
-- TABLE: SMXFINANC.SFDEPTCLOSLOCDOCUMENT
-- ============================================================
CREATE TABLE SMXFINANC.SFDEPTCLOSLOCDOCUMENT (
  DOCUMENTCODE DECIMAL(10) NOT NULL,
  COMPANYCODE INTEGER NOT NULL,
  LOCALCLOSINGCODE DECIMAL(10) NOT NULL,
  CODECLOSETHECAJERO DECIMAL(10),
  AREACODE INTEGER,
  EMPLOYEEREFERENCECODE INTEGER NOT NULL,
  DOCUMENTTYPE INTEGER,
  IMAGE VARCHAR(500) NOT NULL,
  STATUS VARCHAR(1) NOT NULL,
  CREATEDBYUSER VARCHAR(50) NOT NULL,
  CREATEDDATE TIMESTAMP NOT NULL,
  LASTMODIFIEDBYUSER VARCHAR(50),
  LASTMODIFIEDDATE TIMESTAMP,
  VERSION INTEGER NOT NULL,
  CREATEDFROMIP VARCHAR(50),
  UPDATEFROMIP VARCHAR(50),
  PRIMARY KEY (DOCUMENTCODE)
);

-- ============================================================
-- TABLE: SMXFINANC.SFDEPTCONLOC
-- ============================================================
CREATE TABLE SMXFINANC.SFDEPTCONLOC (
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOCONFIGURACIONLOCAL DECIMAL(10) NOT NULL,
  CODIGOAREATRABAJO INTEGER NOT NULL,
  FECHAINICIOCONFIGURACION TIMESTAMP NOT NULL,
  ESMULTIMONEDA VARCHAR(1) NOT NULL,
  ESESTATICO VARCHAR(1),
  FECHAFINCONFIGURACION TIMESTAMP,
  RUTAWEBSERVICES VARCHAR(200),
  RUTAARCHIVO VARCHAR(200),
  ESTADO VARCHAR(1) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  DIASTRANSMISIONJDE INTEGER,
  DIASREPROCESO INTEGER,
  CODIGOCATALOGOTIPOMONEDA INTEGER,
  CODIGOCATALOGOVALORMONEDA VARCHAR(32),
  PRIMARY KEY (CODIGOCONFIGURACIONLOCAL)
);

-- ============================================================
-- TABLE: SMXFINANC.SFDEPTFORPAG
-- ============================================================
CREATE TABLE SMXFINANC.SFDEPTFORPAG (
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOFORMAPAGO DECIMAL(10) NOT NULL,
  CODIGOTRANSACCION DECIMAL(10) NOT NULL,
  CODIGOCATALOGOTIPOFORMAPAGO INTEGER NOT NULL,
  CODIGOCATALOGOVALORFORMAPAGO VARCHAR(32) NOT NULL,
  VALORCORREGIDO DECIMAL(12,2),
  VALORPOS DECIMAL(12,2),
  VALORDIFERENCIA DECIMAL(12,2),
  ESTADO VARCHAR(1) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  PRIMARY KEY (CODIGOFORMAPAGO)
);

-- ============================================================
-- TABLE: SMXFINANC.SFDEPTINTVEN
-- ============================================================
CREATE TABLE SMXFINANC.SFDEPTINTVEN (
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOINTEGRACIONVENTA DECIMAL(10) NOT NULL,
  CODIGOSISTEMA VARCHAR(32) NOT NULL,
  CODIGOAREATRABAJO INTEGER NOT NULL,
  CODIGOCATALOGOTIPOESTADOINTEGRACION INTEGER NOT NULL,
  CODIGOCATALOGOVALORESTADOINTEGRACION VARCHAR(32) NOT NULL,
  NOMBREARCHIVO VARCHAR(32) NOT NULL,
  INFOVENTA XML,
  FECHAVENTA TIMESTAMP,
  FECHALECTURA TIMESTAMP NOT NULL,
  ESTADO VARCHAR(1) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  ESINTEGRACIONMANUAL VARCHAR(1),
  CODIGOCATALOGOTIPOTIPOINTEGRACION INTEGER,
  CODIGOCATALOGOVALORTIPOINTEGRACION VARCHAR(32),
  PRIMARY KEY (CODIGOINTEGRACIONVENTA)
);

-- ============================================================
-- TABLE: SMXFINANC.SFDEPTINTVENDET
-- ============================================================
CREATE TABLE SMXFINANC.SFDEPTINTVENDET (
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOINTEGRACIONVENTADETALLE DECIMAL(10) NOT NULL,
  CODIGOINTEGRACIONVENTA DECIMAL(10) NOT NULL,
  CODIGOCATALOGOTIPOFORMAPAGO INTEGER,
  CODIGOCATALOGOVALORFORMAPAGO VARCHAR(32),
  CODIGOCATALOGOTIPOTIPOPAGO INTEGER,
  CODIGOCATALOGOVALORTIPOPAGO VARCHAR(32),
  CODIGOINSTITUCIONTARJETA DECIMAL(10),
  CODIGOAREATRABAJO INTEGER NOT NULL,
  CANTIDADVENTA INTEGER,
  VALORVENTA DECIMAL(12,2),
  VALORCORREGIDO DECIMAL(12,2),
  OBSERVACION VARCHAR(200),
  FECHAVENTA TIMESTAMP,
  CODIGOTARJETA VARCHAR(32),
  MESESPLAZO INTEGER,
  MESESGRACIA VARCHAR(1),
  CANTIDADVALES INTEGER,
  ESTADO VARCHAR(1) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  PRIMARY KEY (CODIGOINTEGRACIONVENTADETALLE)
);

-- ============================================================
-- TABLE: SMXFINANC.SFDEPTOBSERVACION
-- ============================================================
CREATE TABLE SMXFINANC.SFDEPTOBSERVACION (
  CODIGOCOMPANIA INTEGER,
  CODIGOOBSERVACION DECIMAL(10) NOT NULL,
  CODIGOCIERRELOCAL DECIMAL(10) NOT NULL,
  DESCRIPCION VARCHAR(300) NOT NULL,
  ESTADO VARCHAR(1) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAMODIFICACION TIMESTAMP,
  USUARIOMODIFICACION VARCHAR(32),
  CODIGOCIERRELOCALCAJERO DECIMAL(10),
  CODIGOCATALOGOTIPOOBSERVACION INTEGER,
  CODIGOCATALOGOVALOROBSERVACION VARCHAR(32),
  PRIMARY KEY (CODIGOOBSERVACION)
);

-- ============================================================
-- TABLE: SMXFINANC.SFDEPTPAPDEP
-- ============================================================
CREATE TABLE SMXFINANC.SFDEPTPAPDEP (
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOPAPELETADEPOSITO DECIMAL(10) NOT NULL,
  CODIGOINTEGRACIONVENTADETALLE DECIMAL(10) NOT NULL,
  CODIGOCATALOGOTIPOFORMAPAGO INTEGER NOT NULL,
  CODIGOCATALOGOVALORFORMAPAGO VARCHAR(32) NOT NULL,
  CODIGORESPONSABLE VARCHAR(64),
  CODIGOINSTITUCIONTARJETA DECIMAL(10),
  VALOR DECIMAL(12,2) NOT NULL,
  NUMEROPAPELETA VARCHAR(20) NOT NULL,
  NUMEROCUENTA VARCHAR(30),
  CANTIDADCHEQUE INTEGER,
  FECHADEPOSITO TIMESTAMP NOT NULL,
  FORMADEPOSITO VARCHAR(30),
  OBSERVACION VARCHAR(120),
  ESTADO VARCHAR(1) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  PRIMARY KEY (CODIGOPAPELETADEPOSITO)
);

-- ============================================================
-- TABLE: SMXFINANC.SFDEPTSERIE
-- ============================================================
CREATE TABLE SMXFINANC.SFDEPTSERIE (
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOSERIE DECIMAL(10) NOT NULL,
  CODIGOTIPOPAGO DECIMAL(10) NOT NULL,
  NUMEROSERIEPOS VARCHAR(32),
  CUADRA VARCHAR(1),
  REVISADO VARCHAR(1) NOT NULL,
  NUMEROSERIECORREGIDO VARCHAR(32),
  TIENENOVEDAD VARCHAR(1) NOT NULL,
  CODIGOCATALOGOTIPONOVEDAD INTEGER,
  CODIGOCATALOGOVALORNOVEDAD VARCHAR(32),
  OBSERVACION VARCHAR(200),
  ESTADO VARCHAR(1) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  PRIMARY KEY (CODIGOSERIE)
);

-- ============================================================
-- TABLE: SMXFINANC.SFDEPTTASCAM
-- ============================================================
CREATE TABLE SMXFINANC.SFDEPTTASCAM (
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOTASACAMBIO DECIMAL(10) NOT NULL,
  CODIGOTRANSACCION DECIMAL(10) NOT NULL,
  CODIGOCATALOGOTIPOMONEDA INTEGER,
  CODIGOCATALOGOVALORMONEDA VARCHAR(32),
  TASACONVERSION DECIMAL(12,7),
  ESTADO VARCHAR(1) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  PRIMARY KEY (CODIGOTASACAMBIO)
);

-- ============================================================
-- TABLE: SMXFINANC.SFDEPTTIPPAG
-- ============================================================
CREATE TABLE SMXFINANC.SFDEPTTIPPAG (
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOTIPOPAGO DECIMAL(10) NOT NULL,
  CODIGOFORMAPAGO DECIMAL(10) NOT NULL,
  CODIGOCATALOGOTIPOPAGO INTEGER NOT NULL,
  CODIGOCATALOGOVALORPAGO VARCHAR(32) NOT NULL,
  CODIGOCATALOGOTIPODENOMINACION INTEGER,
  CODIGOCATALOGOVALORDENOMINACION VARCHAR(32),
  CANTIDADPOS INTEGER,
  VALORPOS DECIMAL(12,2),
  CUADRA VARCHAR(1) NOT NULL,
  CANTIDADCORREGIDA INTEGER,
  VALORCORREGIDO DECIMAL(12,2),
  REVISADO VARCHAR(1) NOT NULL,
  NUMERODEPOSITO VARCHAR(10),
  OBSERVACION VARCHAR(120),
  ESTADO VARCHAR(1) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  VALORSISTEMA DECIMAL(12,2),
  CANTIDADSISTEMA INTEGER,
  ESDATOCONTROLADOR INTEGER,
  PRIMARY KEY (CODIGOTIPOPAGO)
);

-- ============================================================
-- TABLE: SMXFINANC.SFDEPTTRANSACCION
-- ============================================================
CREATE TABLE SMXFINANC.SFDEPTTRANSACCION (
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOTRANSACCION DECIMAL(10) NOT NULL,
  CODIGOCIERRELOCALCAJERO DECIMAL(10) NOT NULL,
  CODIGOCATALOGOTIPOTRANSACCION INTEGER NOT NULL,
  CODIGOCATALOGOVALORTRANSACCION VARCHAR(32) NOT NULL,
  VENTASTOTALESNETAS DECIMAL(12,2),
  VALORTOTALTRANSACCION DECIMAL(12,2),
  NUMEROCAJA VARCHAR(32),
  FECHAINICIOCUADRE TIMESTAMP,
  FECHAFINCUADRE TIMESTAMP,
  DIFERENCIAMINUTOS DECIMAL(12,2),
  ESTADO VARCHAR(1) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  SECUENCIALHISTORIALEMPLEADO DECIMAL(10),
  CODIGOEXTERNO VARCHAR(16),
  ESTADOTRANSACCION VARCHAR(16),
  OBSERVACION VARCHAR(150),
  SUPERVISOR DECIMAL(10),
  AUTOMATICO INTEGER,
  FECHATRANSACCION TIMESTAMP,
  PRIMARY KEY (CODIGOTRANSACCION)
);

-- ============================================================
-- TABLE: SMXFINANC.SFGDRTCOMDOC
-- ============================================================
CREATE TABLE SMXFINANC.SFGDRTCOMDOC (
  COMPANY_CODE INTEGER NOT NULL,
  COMMERCIAL_DOCUMENT_CODE VARCHAR(36) NOT NULL,
  EXPENSE_CODE VARCHAR(36) NOT NULL,
  DESTINATION_TYPE INTEGER NOT NULL,
  DESTINATION_CODE VARCHAR(3) NOT NULL,
  COUNTRY_CODE VARCHAR(3) NOT NULL,
  CITY_CODE VARCHAR(10) NOT NULL,
  DOCUMENT_TYPE INTEGER NOT NULL,
  DOCUMENT_CODE VARCHAR(3) NOT NULL,
  DOCUMENT_NUMBER VARCHAR(50),
  TAX_IDENTIFICATION_NUMBER VARCHAR(50),
  DOCUMENT_DATE TIMESTAMP NOT NULL,
  BUSINESS_NAME VARCHAR(50) NOT NULL,
  TOTAL_AMOUNT DECIMAL(10,2) NOT NULL,
  ALLOWED_AMOUNT DECIMAL(10,2),
  AUTHORIZED_AMOUNT DECIMAL(10,2),
  AUTHORIZED CHAR(1),
  REFUND_DOCUMENT VARCHAR(1),
  OBSERVATION VARCHAR(1024),
  STATUS VARCHAR(1) NOT NULL,
  CREATED_BY_USER VARCHAR(50) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL,
  LAST_MODIFIED_BY_USER VARCHAR(50),
  LAST_MODIFIED_DATE TIMESTAMP,
  VERSION INTEGER NOT NULL,
  CREATED_FROM_IP VARCHAR(50) NOT NULL,
  UPDATED_FROM_IP VARCHAR(50),
  PRIMARY KEY (COMMERCIAL_DOCUMENT_CODE)
);

-- ============================================================
-- TABLE: SMXFINANC.SFGDRTCOMDOCDET
-- ============================================================
CREATE TABLE SMXFINANC.SFGDRTCOMDOCDET (
  COMPANY_CODE INTEGER NOT NULL,
  COMDOCDET_CODE VARCHAR(36) NOT NULL,
  COMMERCIAL_DOCUMENT_CODE VARCHAR(36) NOT NULL,
  EXPENSE_CODE VARCHAR(36) NOT NULL,
  ITEM_CODE VARCHAR(36) NOT NULL,
  SIF_CODE DECIMAL(10) NOT NULL,
  PEOPLE_QUANTITY INTEGER NOT NULL,
  ZERO_TAX_AMOUNT DECIMAL(10,2) NOT NULL,
  IVA_TAX_CODE_TYPE INTEGER NOT NULL,
  IVA_TAX_CODE_VALUE VARCHAR(3) NOT NULL,
  IVA_TAX_AMOUNT DECIMAL(10,2) NOT NULL,
  WITHOUT_TAX_SUB_AMOUNT DECIMAL(10,2) NOT NULL,
  IVA_TAX_PERCENTAGE DECIMAL(10,2) NOT NULL,
  IVA_TAX_SUB_AMOUNT DECIMAL(10,2) NOT NULL,
  SERVICE_FEE_PERCENTAGE DECIMAL(10,2) NOT NULL,
  SERVICE_AMOUNT DECIMAL(10,2),
  TOTAL_AMOUNT DECIMAL(10,2) NOT NULL,
  ALLOWED_AMOUNT DECIMAL(10,2) NOT NULL,
  AUTHORIZED_AMOUNT DECIMAL(10,2),
  OBSERVATION VARCHAR(1024),
  STATUS VARCHAR(1) NOT NULL,
  CREATED_BY_USER VARCHAR(50) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL,
  LAST_MODIFIED_BY_USER VARCHAR(50),
  LAST_MODIFIED_DATE TIMESTAMP,
  VERSION INTEGER NOT NULL,
  CREATED_FROM_IP VARCHAR(50) NOT NULL,
  UPDATED_FROM_IP VARCHAR(50),
  PRIMARY KEY (COMDOCDET_CODE)
);

-- ============================================================
-- TABLE: SMXFINANC.SFGDRTCOMDOCFIL
-- ============================================================
CREATE TABLE SMXFINANC.SFGDRTCOMDOCFIL (
  COMPANY_CODE INTEGER NOT NULL,
  COMDOCFIL_CODE VARCHAR(36) NOT NULL,
  COMMERCIAL_DOCUMENT_CODE VARCHAR(36) NOT NULL,
  EXPENSE_CODE VARCHAR(36) NOT NULL,
  FILE_FTP_KEYID VARCHAR(128) NOT NULL,
  FILE_NAME VARCHAR(64) NOT NULL,
  FILE_EXTENSION VARCHAR(5) NOT NULL,
  FILE_TYPE VARCHAR(32),
  FILE_SIZE DECIMAL(10,2) NOT NULL,
  STATUS VARCHAR(1) NOT NULL,
  CREATED_BY_USER VARCHAR(50) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL,
  LAST_MODIFIED_BY_USER VARCHAR(50),
  LAST_MODIFIED_DATE TIMESTAMP,
  VERSION INTEGER NOT NULL,
  CREATED_FROM_IP VARCHAR(50) NOT NULL,
  UPDATED_FROM_IP VARCHAR(50),
  PRIMARY KEY (COMDOCFIL_CODE)
);

-- ============================================================
-- TABLE: SMXFINANC.SFGDRTCOMDOCPER
-- ============================================================
CREATE TABLE SMXFINANC.SFGDRTCOMDOCPER (
  COMPANY_CODE INTEGER NOT NULL,
  COMDOCPER_CODE VARCHAR(36) NOT NULL,
  COMMERCIAL_DOCUMENT_CODE VARCHAR(36) NOT NULL,
  EXPENSE_CODE VARCHAR(36) NOT NULL,
  FUNCTIONARY_USER_ID VARCHAR(32),
  USER_NAME VARCHAR(64),
  USER_FULL_NAME VARCHAR(128),
  FUNCTIONARY_ID VARCHAR(64),
  IDENTIFICATION VARCHAR(20),
  COLLABORATOR_ID INTEGER,
  JDE_CODE INTEGER,
  PERSON_CODE DECIMAL(10),
  CLIENT_CODE INTEGER,
  POSITION_ID INTEGER,
  POSITION_NAME VARCHAR(150),
  WORK_AREA_CODE INTEGER,
  WORK_SUBAREA_CODE INTEGER,
  COST_CENTRE VARCHAR(32),
  REQUEST_STATUS VARCHAR(1) NOT NULL,
  STATUS VARCHAR(1) NOT NULL,
  CREATED_BY_USER VARCHAR(50) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL,
  LAST_MODIFIED_BY_USER VARCHAR(50),
  LAST_MODIFIED_DATE TIMESTAMP,
  VERSION INTEGER NOT NULL,
  CREATED_FROM_IP VARCHAR(50) NOT NULL,
  UPDATED_FROM_IP VARCHAR(50),
  PRIMARY KEY (COMDOCPER_CODE)
);

-- ============================================================
-- TABLE: SMXFINANC.SFGDRTEXPENSE
-- ============================================================
CREATE TABLE SMXFINANC.SFGDRTEXPENSE (
  COMPANY_CODE INTEGER NOT NULL,
  EXPENSE_CODE VARCHAR(36) NOT NULL,
  EXPENSE_CODE_VALUE VARCHAR(3) NOT NULL,
  EXPENSE_CREATOR_PERSON_CODE DECIMAL(10) NOT NULL,
  PERSON_CODE DECIMAL(10) NOT NULL,
  FLUX_CODE VARCHAR(20),
  ADVANCE_AMOUNT DECIMAL(10,2),
  WORKAREA_CODE INTEGER NOT NULL,
  SUBWORKAREA_CODE INTEGER NOT NULL,
  COST_CENTRE VARCHAR(32) NOT NULL,
  MOTIVATION_CODE_VALUE VARCHAR(3) NOT NULL,
  DESTINATION_DESCRIPTION VARCHAR(256) NOT NULL,
  OTHER_MOTIVATION_DESCRIPTION VARCHAR(256),
  SEND_DATE TIMESTAMP,
  INITIAL_PERIOD_DATE TIMESTAMP NOT NULL,
  FINAL_PERIOD_DATE TIMESTAMP NOT NULL,
  TOTAL_AMOUNT DECIMAL(10,2) NOT NULL,
  ALLOWED_AMOUNT DECIMAL(10,2) NOT NULL,
  AUTHORIZED_AMOUNT DECIMAL(10,2),
  AUTHORIZED CHAR(1),
  OBSERVATION VARCHAR(1024),
  REQUEST_STATUS_TYPE INTEGER NOT NULL,
  REQUEST_STATUS VARCHAR(3) NOT NULL,
  REFUND_DOCUMENT VARCHAR(1),
  DOCUMENT_CODE_LIQUIDATION DECIMAL(10),
  DOCUMENT_NUMBER_LIQUIDATION VARCHAR(50),
  STATUS VARCHAR(1) NOT NULL,
  CREATED_BY_USER VARCHAR(50) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL,
  LAST_MODIFIED_BY_USER VARCHAR(50),
  LAST_MODIFIED_DATE TIMESTAMP,
  VERSION INTEGER NOT NULL,
  CREATED_FROM_IP VARCHAR(50) NOT NULL,
  UPDATED_FROM_IP VARCHAR(50),
  PRIMARY KEY (EXPENSE_CODE)
);

-- ============================================================
-- TABLE: SMXFINANC.SFGDRTEXPFLO
-- ============================================================
CREATE TABLE SMXFINANC.SFGDRTEXPFLO (
  COMPANY_CODE INTEGER NOT NULL,
  EXPENSE_FLOW_CODE VARCHAR(36) NOT NULL,
  EXPENSE_CODE VARCHAR(36) NOT NULL,
  START_FLOW_TYPE INTEGER NOT NULL,
  START_FLOW VARCHAR(3) NOT NULL,
  END_FLOW_TYPE INTEGER NOT NULL,
  END_FLOW VARCHAR(3) NOT NULL,
  START_FLOW_DATE TIMESTAMP NOT NULL,
  END_FLOW_DATE TIMESTAMP,
  PERSON_CODE_MANAGER DECIMAL(10),
  OBSERVATION VARCHAR(1024),
  STATUS VARCHAR(1) NOT NULL,
  CREATED_BY_USER VARCHAR(50) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL,
  LAST_MODIFIED_BY_USER VARCHAR(50),
  LAST_MODIFIED_DATE TIMESTAMP,
  VERSION INTEGER NOT NULL,
  CREATED_FROM_IP VARCHAR(50) NOT NULL,
  UPDATED_FROM_IP VARCHAR(50),
  PRIMARY KEY (EXPENSE_FLOW_CODE)
);

-- ============================================================
-- TABLE: SMXFINANC.SFGDRTITEM
-- ============================================================
CREATE TABLE SMXFINANC.SFGDRTITEM (
  COMPANY_CODE INTEGER NOT NULL,
  ITEM_CODE VARCHAR(36) NOT NULL,
  SIF_CODE DECIMAL(10) NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(256),
  DESTINATION_TYPE INTEGER NOT NULL,
  DESTINATION_CODE VARCHAR(3) NOT NULL,
  COUNTRY_CODE VARCHAR(10) NOT NULL,
  CITY_CODE VARCHAR(10) NOT NULL,
  DAILY_FREQUENCY INTEGER,
  DEFAULT_VALUE VARCHAR(1) NOT NULL,
  STATUS VARCHAR(1) NOT NULL,
  CREATED_BY_USER VARCHAR(50) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL,
  LAST_MODIFIED_BY_USER VARCHAR(50),
  LAST_MODIFIED_DATE TIMESTAMP,
  VERSION INTEGER NOT NULL,
  CREATED_FROM_IP VARCHAR(50) NOT NULL,
  UPDATED_FROM_IP VARCHAR(50),
  ENABLE_DAYS VARCHAR(1),
  PRIMARY KEY (ITEM_CODE)
);

-- ============================================================
-- TABLE: SMXFINANC.SFGDRTITEMTAX
-- ============================================================
CREATE TABLE SMXFINANC.SFGDRTITEMTAX (
  COMPANY_CODE INTEGER NOT NULL,
  TAX_CODE VARCHAR(36) NOT NULL,
  ITEM_CODE VARCHAR(36) NOT NULL,
  ALLOWED_VALUE DECIMAL(10,2) NOT NULL,
  IVA_TAX_APPLIES VARCHAR(1) NOT NULL,
  IVA_TAX_PERCENTAGE DECIMAL(10,2) NOT NULL,
  SERVICE_FEE_APPLIES VARCHAR(1) NOT NULL,
  SERVICE_FEE_PERCENTAGE DECIMAL(10,2) NOT NULL,
  STATUS VARCHAR(1) NOT NULL,
  CREATED_BY_USER VARCHAR(50) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL,
  LAST_MODIFIED_BY_USER VARCHAR(50),
  LAST_MODIFIED_DATE TIMESTAMP,
  VERSION INTEGER NOT NULL,
  CREATED_FROM_IP VARCHAR(50) NOT NULL,
  UPDATED_FROM_IP VARCHAR(50),
  PRIMARY KEY (TAX_CODE)
);

-- ============================================================
-- TABLE: SMXFINANC.SFGDRTROLE
-- ============================================================
CREATE TABLE SMXFINANC.SFGDRTROLE (
  COMPANY_CODE INTEGER NOT NULL,
  ROLE_CODE VARCHAR(36) NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(256),
  STATUS VARCHAR(1) NOT NULL,
  CREATED_BY_USER VARCHAR(50) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL,
  LAST_MODIFIED_BY_USER VARCHAR(50),
  LAST_MODIFIED_DATE TIMESTAMP,
  VERSION INTEGER NOT NULL,
  CREATED_FROM_IP VARCHAR(50) NOT NULL,
  UPDATED_FROM_IP VARCHAR(50),
  PRIMARY KEY (ROLE_CODE)
);

-- ============================================================
-- TABLE: SMXFINANC.SFGDRTUSEARE
-- ============================================================
CREATE TABLE SMXFINANC.SFGDRTUSEARE (
  COMPANY_CODE INTEGER NOT NULL,
  USER_AREA_CODE VARCHAR(36) NOT NULL,
  USER_CODE VARCHAR(36) NOT NULL,
  WORK_AREA_CODE INTEGER NOT NULL,
  SUB_WORK_AREA_CODE INTEGER NOT NULL,
  STATUS VARCHAR(1) NOT NULL,
  CREATED_BY_USER VARCHAR(50) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL,
  LAST_MODIFIED_BY_USER VARCHAR(50),
  LAST_MODIFIED_DATE TIMESTAMP,
  VERSION INTEGER NOT NULL,
  CREATED_FROM_IP VARCHAR(50) NOT NULL,
  UPDATED_FROM_IP VARCHAR(50),
  PRIMARY KEY (USER_AREA_CODE)
);

-- ============================================================
-- TABLE: SMXFINANC.SFGDRTUSER
-- ============================================================
CREATE TABLE SMXFINANC.SFGDRTUSER (
  COMPANY_CODE INTEGER NOT NULL,
  USER_CODE VARCHAR(36) NOT NULL,
  USER_ID VARCHAR(64) NOT NULL,
  FUNCTIONARY_CODE VARCHAR(64),
  PERSON_CODE DECIMAL(10) NOT NULL,
  EMPLOYEE_CODE VARCHAR(64),
  JDE_CODE INTEGER,
  STATUS VARCHAR(1) NOT NULL,
  CREATED_BY_USER VARCHAR(50) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL,
  LAST_MODIFIED_BY_USER VARCHAR(50),
  LAST_MODIFIED_DATE TIMESTAMP,
  VERSION INTEGER NOT NULL,
  CREATED_FROM_IP VARCHAR(50) NOT NULL,
  UPDATED_FROM_IP VARCHAR(50),
  PRIMARY KEY (USER_CODE)
);

-- ============================================================
-- TABLE: SMXFINANC.SFGDRTUSEROL
-- ============================================================
CREATE TABLE SMXFINANC.SFGDRTUSEROL (
  COMPANY_CODE INTEGER NOT NULL,
  USER_ROLE_CODE VARCHAR(36) NOT NULL,
  USER_CODE VARCHAR(36) NOT NULL,
  ROLE_CODE VARCHAR(36) NOT NULL,
  STATUS VARCHAR(1) NOT NULL,
  CREATED_BY_USER VARCHAR(50) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL,
  LAST_MODIFIED_BY_USER VARCHAR(50),
  LAST_MODIFIED_DATE TIMESTAMP,
  VERSION INTEGER NOT NULL,
  CREATED_FROM_IP VARCHAR(50) NOT NULL,
  UPDATED_FROM_IP VARCHAR(50),
  PRIMARY KEY (USER_ROLE_CODE)
);

-- ============================================================
-- TABLE: SMXFINANC.SFGTFTARETRADEPREP
-- ============================================================
CREATE TABLE SMXFINANC.SFGTFTARETRADEPREP (
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOAREATRABAJO INTEGER NOT NULL,
  REALIZADEPOSITO VARCHAR(1) NOT NULL,
  PORCENTAJEUSO DECIMAL(5,2) NOT NULL,
  VALORCAJACHICA DECIMAL(12,2) NOT NULL,
  CODCATVALFORDEP VARCHAR(3) NOT NULL,
  CODCATTIPFORDEP INTEGER NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  PRIMARY KEY (CODIGOCOMPANIA, CODIGOAREATRABAJO)
);

-- ============================================================
-- TABLE: SMXFINANC.SFGTFTARETRAFIN
-- ============================================================
CREATE TABLE SMXFINANC.SFGTFTARETRAFIN (
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOAREATRABAJO INTEGER NOT NULL,
  REALIZADEPOSITO VARCHAR(1) NOT NULL,
  PORCENTAJEUSO DECIMAL(5,2) NOT NULL,
  FONDOASIGNADO DECIMAL(12,2) NOT NULL,
  REPOSICIONESPENDIENTESPAGO DECIMAL(12,2) NOT NULL,
  SALDOEFECTIVO DECIMAL(12,2) NOT NULL,
  CODCATVALFORDEP VARCHAR(3) NOT NULL,
  CODCATTIPFORDEP INTEGER NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  VALORMAXIMODOCUMENTO DECIMAL(12,2),
  PORCENTAJEALERTA DECIMAL(5,2),
  PAGOCHEQUE VARCHAR(3),
  PRIMARY KEY (CODIGOCOMPANIA, CODIGOAREATRABAJO)
);

-- ============================================================
-- TABLE: SMXFINANC.SFGTFTDEPOSITO
-- ============================================================
CREATE TABLE SMXFINANC.SFGTFTDEPOSITO (
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGODEPOSITO DECIMAL(10) NOT NULL,
  CODIGOAREATRABAJO INTEGER NOT NULL,
  CODIGOLOCAL INTEGER NOT NULL,
  CODIGODEPOSITORELACIONADO DECIMAL(10),
  CODIGOPERSONA DECIMAL(10) NOT NULL,
  FECHADEPOSITO TIMESTAMP NOT NULL,
  FECHAVENTA TIMESTAMP NOT NULL,
  NUMEROPAPELETA VARCHAR(64),
  NUMEROGUIA VARCHAR(64),
  VALORTOTALEFECTIVO DECIMAL(12,2),
  VALORTOTALCHEQUE DECIMAL(12,2),
  VALORTOTALVENTA DECIMAL(12,2) NOT NULL,
  ESTADO VARCHAR(1) NOT NULL,
  CODCATVALESTDEP VARCHAR(3) NOT NULL,
  CODCATTIPESTDEP INTEGER NOT NULL,
  CODCATVALFORDEP VARCHAR(3) NOT NULL,
  CODCATTIPFORDEP INTEGER NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  OBSERVACION VARCHAR(500),
  PRIMARY KEY (CODIGOCOMPANIA, CODIGODEPOSITO)
);

-- ============================================================
-- TABLE: SMXFINANC.SFGTFTDETALLEDEPOSITO
-- ============================================================
CREATE TABLE SMXFINANC.SFGTFTDETALLEDEPOSITO (
  CODIGOCOMPANIA INTEGER NOT NULL,
  SECUENCIALDETALLE DECIMAL(10) NOT NULL,
  CODIGODEPOSITO DECIMAL(10) NOT NULL,
  CODIGODENOMINACION DECIMAL(10) NOT NULL,
  CANTIDAD DECIMAL(7) NOT NULL,
  TOTALDETALLE DECIMAL(12,2) NOT NULL,
  ESTADO VARCHAR(1) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  PRIMARY KEY (CODIGOCOMPANIA, SECUENCIALDETALLE, CODIGODEPOSITO)
);

-- ============================================================
-- TABLE: SMXFINANC.SFGTFTDETALLEMOVIMIENTO
-- ============================================================
CREATE TABLE SMXFINANC.SFGTFTDETALLEMOVIMIENTO (
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOREPOSICIONESTADO DECIMAL(10),
  CODIGOAREATRABAJO INTEGER NOT NULL,
  SECUENCIALMOVIMIENTO DECIMAL(10) NOT NULL,
  CODCATVALTRATIP VARCHAR(3) NOT NULL,
  CODCATTIPTRATIP INTEGER NOT NULL,
  VALOR DECIMAL(12,2) NOT NULL,
  OBSERVACION VARCHAR(100),
  ESTADO VARCHAR(1) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  PRIMARY KEY (CODIGOCOMPANIA, SECUENCIALMOVIMIENTO)
);

-- ============================================================
-- TABLE: SMXFINANC.SFGTFTDETALLEREPOSICION
-- ============================================================
CREATE TABLE SMXFINANC.SFGTFTDETALLEREPOSICION (
  CODIGOCOMPANIA INTEGER NOT NULL,
  SECUENCIALDETALLE DECIMAL(10) NOT NULL,
  CODIGOREPOSICION DECIMAL(10) NOT NULL,
  SECCONARETRA INTEGER NOT NULL,
  NUMERORUCFACTURA VARCHAR(20),
  NUMERODOCUMENTO VARCHAR(20),
  FECHACONCEPTO TIMESTAMP NOT NULL,
  OBSERVACION VARCHAR(800) NOT NULL,
  OBSERVACIONVALIDACION VARCHAR(800),
  ESTADODETALLE VARCHAR(1) NOT NULL,
  VALORDETALLEREPOSICION DECIMAL(12,2) NOT NULL,
  VALORAPROBADO DECIMAL(12,2),
  VALORIVA DECIMAL(12,2) NOT NULL,
  VALORIVAAPROBADO DECIMAL(12,2),
  CODCATVALDOCTIP VARCHAR(3) NOT NULL,
  CODCATTIPDOCTIP INTEGER NOT NULL,
  CODCATVALTIPVIA VARCHAR(3),
  CODCATTIPVIATIP INTEGER,
  CODDIVGEOPOLPAI VARCHAR(10),
  CODDIVGEOPOLCIU VARCHAR(10),
  CODIGOMONEDA DECIMAL(10),
  CODIGOCAMBIOMONEDA DECIMAL(10),
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  COMPROBANTEVENTA VARCHAR(20),
  CODIGOFACTURA DECIMAL(15),
  CODIGOACCESO VARCHAR(50),
  BASE0 DECIMAL(12,2),
  BASE0APROBADO DECIMAL(12,2),
  BASE12 DECIMAL(12,2),
  BASE12APROBADO DECIMAL(12,2),
  CANTIDAD DECIMAL(7,2),
  CODTIPUNIMED INTEGER,
  CODVALUNIMED VARCHAR(3),
  TIPOARCHIVO VARCHAR(40),
  NOMBREARCHIVO VARCHAR(100),
  PRIMARY KEY (CODIGOCOMPANIA, SECUENCIALDETALLE, CODIGOREPOSICION)
);

-- ============================================================
-- TABLE: SMXFINANC.SFGTFTDETCONRET
-- ============================================================
CREATE TABLE SMXFINANC.SFGTFTDETCONRET (
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGODETALLECONCEPTORETENCION DECIMAL(15) NOT NULL,
  SECUENCIALDETALLE DECIMAL(10) NOT NULL,
  CODIGOREPOSICION DECIMAL(10) NOT NULL,
  CODIGOCATVALIMP VARCHAR(3) NOT NULL,
  CODIGOCATTIPIMP INTEGER NOT NULL,
  VALORRETENIDO DECIMAL(14,4) NOT NULL,
  ESTADO VARCHAR(1),
  FECHAREGISTRO TIMESTAMP,
  FECHAACTUALIZACION TIMESTAMP,
  USUARIOREGISTRO VARCHAR(32),
  USUARIOMODIFICACION VARCHAR(32),
  PRIMARY KEY (CODIGOCOMPANIA, CODIGODETALLECONCEPTORETENCION)
);

-- ============================================================
-- TABLE: SMXFINANC.SFGTFTDETDEPCON
-- ============================================================
CREATE TABLE SMXFINANC.SFGTFTDETDEPCON (
  CODIGOCOMPANIA INTEGER NOT NULL,
  SECDETDEPCON DECIMAL(10) NOT NULL,
  CODIGODEPOSITO DECIMAL(10) NOT NULL,
  CODCATVALCONDETDEP VARCHAR(3) NOT NULL,
  CODCATTIPCONDETDEP INTEGER NOT NULL,
  VALORCONCEPTO DECIMAL(12,2) NOT NULL,
  ESTADO VARCHAR(1) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  PRIMARY KEY (CODIGOCOMPANIA, SECDETDEPCON, CODIGODEPOSITO)
);

-- ============================================================
-- TABLE: SMXFINANC.SFGTFTPARAMETRO
-- ============================================================
CREATE TABLE SMXFINANC.SFGTFTPARAMETRO (
  CODIGOPARAMETRO VARCHAR(10) NOT NULL,
  DESCRIPCIONPARAMETRO VARCHAR(200) NOT NULL,
  VALORPARAMETRO VARCHAR(1000) NOT NULL,
  ESTADO VARCHAR(1) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  PRIMARY KEY (CODIGOPARAMETRO)
);

-- ============================================================
-- TABLE: SMXFINANC.SFGTFTREPOSICIONESTADO
-- ============================================================
CREATE TABLE SMXFINANC.SFGTFTREPOSICIONESTADO (
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOREPOSICION DECIMAL(10) NOT NULL,
  CODIGOREPOSICIONESTADO DECIMAL(10) NOT NULL,
  CODCATVALESTREP VARCHAR(3) NOT NULL,
  CODCATTIPESTREP INTEGER NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  PRIMARY KEY (CODIGOCOMPANIA, CODIGOREPOSICIONESTADO)
);

-- ============================================================
-- TABLE: SMXFINANC.SFGTFTSOLICITUDDOCUMENTO
-- ============================================================
CREATE TABLE SMXFINANC.SFGTFTSOLICITUDDOCUMENTO (
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOREPOSICION DECIMAL(10) NOT NULL,
  CODIGODOCUMENTO DECIMAL(10) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  PRIMARY KEY (CODIGOCOMPANIA, CODIGOREPOSICION, CODIGODOCUMENTO)
);

-- ============================================================
-- TABLE: SMXFINANC.SFGTFTSOLICITUDREPOSICION
-- ============================================================
CREATE TABLE SMXFINANC.SFGTFTSOLICITUDREPOSICION (
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOREPOSICION DECIMAL(10) NOT NULL,
  CODIGOAREATRABAJO INTEGER NOT NULL,
  CODIGOTRANSACCION VARCHAR(32) NOT NULL,
  CODIGOPERSONARESPONSABLE DECIMAL(10) NOT NULL,
  CODIGOPERSONABENEFICIARIO DECIMAL(10),
  CODIGOPERSONARESPONSABLECHEQUE DECIMAL(10),
  CODCATVALESTSOL VARCHAR(3) NOT NULL,
  CODCATTIPESTSOL INTEGER NOT NULL,
  OBSERVACION VARCHAR(100),
  ALERTAENVIOREPOSICION VARCHAR(1),
  VALORANTICIPO DECIMAL(12,2),
  VALORTOTAL DECIMAL(12,2) NOT NULL,
  VALORSUBTOTAL DECIMAL(12,2) NOT NULL,
  TOTALIVA DECIMAL(12,2) NOT NULL,
  TOTALIVAAPROBADO DECIMAL(12,2),
  ESTADOSOLICITUD VARCHAR(1) NOT NULL,
  FECHAINICIO TIMESTAMP,
  FECHAFIN TIMESTAMP,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  BASE0 DECIMAL(12,2),
  BASE12 DECIMAL(12,2),
  PRIMARY KEY (CODIGOCOMPANIA, CODIGOREPOSICION)
);

-- ============================================================
-- TABLE: SMXFINANC.SFGTFTSOLREPDOC
-- ============================================================
CREATE TABLE SMXFINANC.SFGTFTSOLREPDOC (
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOREPOSICION DECIMAL(10) NOT NULL,
  CODIGODOCUMENTO DECIMAL(10) NOT NULL,
  SECUENCIALSOLREPDOC DECIMAL(10) NOT NULL,
  CODIGOAREATRABAJO INTEGER NOT NULL,
  CODCATVALESTSOL VARCHAR(3) NOT NULL,
  CODCATTIPESTSOL INTEGER NOT NULL,
  VALORTOTAL DECIMAL(12,2),
  FECHAREPOSICION TIMESTAMP,
  ESTADO VARCHAR(1),
  FECHAREGISTRO TIMESTAMP,
  FECHAACTUALIZACION TIMESTAMP,
  USUARIOREGISTRO VARCHAR(32),
  USUARIOMODIFICACION VARCHAR(32),
  PRIMARY KEY (CODIGOCOMPANIA, SECUENCIALSOLREPDOC)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSBTLOCADM
-- ============================================================
CREATE TABLE SMXFINANC.SFSBTLOCADM (
  COMPANY_CODE INTEGER NOT NULL,
  LOCAL_ADMINISTRATION_CODE VARCHAR(36) NOT NULL,
  WORK_AREA_CODE INTEGER,
  DESCRIPTION VARCHAR(200),
  URL_WEB_SERVICES VARCHAR(200),
  STATUS SMALLINT NOT NULL,
  CREATED_BY_USER VARCHAR(50) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL,
  CREATED_FROM_IP VARCHAR(50) NOT NULL,
  LAST_MODIFIED_BY_USER VARCHAR(50),
  LAST_MODIFIED_DATE TIMESTAMP,
  UPDATED_FROM_IP VARCHAR(50),
  VERSION INTEGER,
  PRIMARY KEY (COMPANY_CODE, LOCAL_ADMINISTRATION_CODE)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSBTPARAMETER
-- ============================================================
CREATE TABLE SMXFINANC.SFSBTPARAMETER (
  COMPANY_CODE INTEGER NOT NULL,
  PARAMETER_CODE VARCHAR(36) NOT NULL,
  NAME VARCHAR(100),
  DESCRIPTION VARCHAR(200),
  VALUE VARCHAR(200),
  STATUS SMALLINT NOT NULL,
  CREATED_BY_USER VARCHAR(50) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL,
  CREATED_FROM_IP VARCHAR(50) NOT NULL,
  LAST_MODIFIED_BY_USER VARCHAR(50),
  LAST_MODIFIED_DATE TIMESTAMP,
  UPDATED_FROM_IP VARCHAR(50),
  VERSION INTEGER,
  PRIMARY KEY (COMPANY_CODE, PARAMETER_CODE)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSBTSALINTFORTICSER
-- ============================================================
CREATE TABLE SMXFINANC.SFSBTSALINTFORTICSER (
  COMPANY_CODE INTEGER NOT NULL,
  SALES_INTEGRATION_TICKET_CODE VARCHAR(36) NOT NULL,
  WORK_AREA_CODE INTEGER,
  DESCRIPTION VARCHAR(200),
  TOTAL DECIMAL(10,2),
  QUANTITY INTEGER,
  INTEGRATION_DATE TIMESTAMP,
  STATUS SMALLINT NOT NULL,
  CREATED_BY_USER VARCHAR(50) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL,
  CREATED_FROM_IP VARCHAR(50) NOT NULL,
  LAST_MODIFIED_BY_USER VARCHAR(50),
  LAST_MODIFIED_DATE TIMESTAMP,
  UPDATED_FROM_IP VARCHAR(50),
  VERSION INTEGER,
  PRIMARY KEY (COMPANY_CODE, SALES_INTEGRATION_TICKET_CODE)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSBTSALINTFORTICSERDET
-- ============================================================
CREATE TABLE SMXFINANC.SFSBTSALINTFORTICSERDET (
  COMPANY_CODE INTEGER NOT NULL,
  SALES_INTEGRATION_TICKET_DETAIL_CODE VARCHAR(36) NOT NULL,
  SALES_INTEGRATION_TICKET_CODE VARCHAR(36),
  DENOMINATION_CATALOG_VALUE VARCHAR(3),
  DENOMINATION_CATALOG_TYPE INTEGER,
  SERIAL_NUMBER VARCHAR(50),
  DESCRIPTION VARCHAR(200),
  VALUE DECIMAL(10,2),
  STATUS SMALLINT NOT NULL,
  CREATED_BY_USER VARCHAR(50) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL,
  CREATED_FROM_IP VARCHAR(50) NOT NULL,
  LAST_MODIFIED_BY_USER VARCHAR(50),
  LAST_MODIFIED_DATE TIMESTAMP,
  UPDATED_FROM_IP VARCHAR(50),
  VERSION INTEGER,
  PRIMARY KEY (COMPANY_CODE, SALES_INTEGRATION_TICKET_DETAIL_CODE)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSBTTICDECFOR
-- ============================================================
CREATE TABLE SMXFINANC.SFSBTTICDECFOR (
  COMPANY_CODE INTEGER NOT NULL,
  TICKET_DECLARATION_CODE VARCHAR(36) NOT NULL,
  STATUS_CATALOG_TYPE INTEGER,
  STATUS_CATALOG_VALUE VARCHAR(3),
  FORM_CATALOG_TYPE INTEGER,
  FORM_CATALOG_VALUE VARCHAR(3),
  WORK_AREA_CODE INTEGER,
  ACCOUNT_NUMBER VARCHAR(50),
  HEADLINE VARCHAR(100),
  TOTAL_VALUE DECIMAL(10,2),
  CONFIRMATION_DATE TIMESTAMP,
  CONFIRMATION_CITY VARCHAR(50),
  DESCRIPTION VARCHAR(200),
  AGENCY VARCHAR(100),
  CASHIER VARCHAR(100),
  SUPERVISOR VARCHAR(100),
  DEPOSITOR_NAME VARCHAR(250),
  DEPOSITOR_DOCUMENT_NUMBER VARCHAR(20),
  DEPOSITOR_TYPE_DOCUMENT VARCHAR(10),
  DESCRIPTION_CANCELED VARCHAR(250),
  STATUS SMALLINT NOT NULL,
  CREATED_BY_USER VARCHAR(50) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL,
  CREATED_FROM_IP VARCHAR(50) NOT NULL,
  LAST_MODIFIED_BY_USER VARCHAR(50),
  LAST_MODIFIED_DATE TIMESTAMP,
  UPDATED_FROM_IP VARCHAR(50),
  VERSION INTEGER,
  PRIMARY KEY (COMPANY_CODE, TICKET_DECLARATION_CODE)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSBTTICDECFORDET
-- ============================================================
CREATE TABLE SMXFINANC.SFSBTTICDECFORDET (
  COMPANY_CODE INTEGER NOT NULL,
  TICKET_DECLARATION_DET_CODE VARCHAR(36) NOT NULL,
  TICKET_DECLARATION_CODE VARCHAR(36),
  DENOMINATION_CATALOG_TYPE INTEGER,
  DENOMINATION_CATALOG_VALUE VARCHAR(3),
  DESCRIPTION VARCHAR(200),
  SERIAL_NUMBER VARCHAR(50),
  VALUE DECIMAL(10,2),
  STATUS SMALLINT,
  CREATED_BY_USER VARCHAR(50) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL,
  CREATED_FROM_IP VARCHAR(50) NOT NULL,
  LAST_MODIFIED_BY_USER VARCHAR(50),
  LAST_MODIFIED_DATE TIMESTAMP,
  UPDATED_FROM_IP VARCHAR(50),
  VERSION INTEGER,
  PRIMARY KEY (COMPANY_CODE, TICKET_DECLARATION_DET_CODE)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTANULACION
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTANULACION (
  CODIGOANULACION DECIMAL(16) NOT NULL,
  CODIGODOCUMENTO DECIMAL(16),
  RESPONSABLE VARCHAR(100),
  FECHASOLICITUD TIMESTAMP,
  VALOR DECIMAL(15,2),
  OBSERVACION VARCHAR(2000),
  OBSERVACIONRESPUESTA VARCHAR(2000),
  OBSERVACIONREVERSO VARCHAR(2000),
  ESTADOANULACION VARCHAR(3),
  ESTADO VARCHAR(3) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  OTRASCUENTAS SMALLINT,
  PRIMARY KEY (CODIGOANULACION)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTANUVEN
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTANUVEN (
  CODIGOANUVEN DECIMAL(16) NOT NULL,
  CODIGOVENTA DECIMAL(16) NOT NULL,
  CODIGOANULACION DECIMAL(16) NOT NULL,
  ESTADOVENTAPREVIO VARCHAR(3) NOT NULL,
  ESTADO VARCHAR(3) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  ESTADOTRANSMISION VARCHAR(3),
  PRIMARY KEY (CODIGOANUVEN)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTBITAJUSTE
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTBITAJUSTE (
  CODIGOBITAJUSTE DECIMAL(16) NOT NULL,
  CODIGOCONAJUSTE DECIMAL(16) NOT NULL,
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOPROCESADORA DECIMAL(10) NOT NULL,
  CODIGOCONPERIODO DECIMAL(16) NOT NULL,
  CODIGOLOCAL INTEGER,
  TIPOCREDITO VARCHAR(20),
  FECHAAJUSTE DATE,
  FECHACONTABLE DATE,
  FECHAPAGO DATE,
  IVARETENCION DECIMAL(15,2),
  RETENCION DECIMAL(15,2),
  VALORLIQUIDADO DECIMAL(15,2) NOT NULL,
  VALORPAGADO DECIMAL(15,2) NOT NULL,
  CONSUMO DECIMAL(15,2) NOT NULL,
  CONSUMOMASIVA DECIMAL(15,2) NOT NULL,
  COMISION DECIMAL(15,2) NOT NULL,
  IVA DECIMAL(15,2) NOT NULL,
  IVA0 DECIMAL(15,2) NOT NULL,
  VALORTOTAL DECIMAL(15,2) NOT NULL,
  VALORNETO DECIMAL(15,2) NOT NULL,
  ESTADO VARCHAR(3) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  ESTADOTRANSMISION VARCHAR(3),
  CODIGOCONEGRESO DECIMAL(16),
  ESTADOCONAJUSTETIPO INTEGER NOT NULL,
  ESTADOCONAJUSTEVALOR VARCHAR(3) NOT NULL,
  OBSERVACION VARCHAR(2000),
  CODIGORECIBO DECIMAL(10),
  VALORCONTABLE DECIMAL(15,2),
  CODIGOCONPARAM DECIMAL(16),
  CARGAMANUAL SMALLINT,
  NUMEROFACTURA VARCHAR(30),
  PRIMARY KEY (CODIGOBITAJUSTE)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTBITCUO
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTBITCUO (
  CODIGOBITCUO DECIMAL(18) NOT NULL,
  CODIGOCUOTA DECIMAL(18) NOT NULL,
  CODIGOVENTA DECIMAL(16),
  NUMEROCUOTA DECIMAL(3) NOT NULL,
  VALORESTIMADO DECIMAL(15,2),
  FECHAESTIMADACOBRO TIMESTAMP,
  FECHAPROCESADORA TIMESTAMP,
  VALORREAL DECIMAL(15,2),
  FECHAREALCOBRO TIMESTAMP,
  ESTADOCUOTA VARCHAR(3),
  ESTADOREGISTROCUOTA VARCHAR(3),
  USUARIOREGISTROCUOTA VARCHAR(32) NOT NULL,
  FECHAREGISTROCUOTA TIMESTAMP NOT NULL,
  USUARIOMODIFICACIONCUOTA VARCHAR(32),
  FECHAMODIFICACIONCUOTA TIMESTAMP,
  ESTADO VARCHAR(3),
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  PRIMARY KEY (CODIGOBITCUO)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTBITPAG
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTBITPAG (
  CODIGOBITACORAPAGO DECIMAL(16) NOT NULL,
  CODIGOPAGO DECIMAL(16) NOT NULL,
  CODIGOCARGA DECIMAL(16),
  CODIGOCOMPANIA INTEGER NOT NULL,
  CIUDADEMISION VARCHAR(3),
  FECHAPROCESODATOS TIMESTAMP,
  CODIGOPROCESADORAARCHIVO VARCHAR(5),
  CODIGOPROCESADORA DECIMAL(10),
  NOMBREPROCESADORA VARCHAR(50),
  MONEDA VARCHAR(5),
  NUMEROVALEGENERADO DECIMAL(14),
  NUMERORECAPGENERADO DECIMAL(14),
  VALORLIQUIDADO DECIMAL(15,2),
  REFERENCIATRANSFERENCIA VARCHAR(20),
  TIPODOCUMENTOARCHIVO DECIMAL(5),
  TIPOCREDITOVENTAARCHIVO DECIMAL(5),
  CODIGOVTC DECIMAL(18),
  MIGRADO VARCHAR(1),
  FECHAPAGO TIMESTAMP,
  CODIGOESTABLECIMIENTO VARCHAR(32),
  CODIGOLOCAL INTEGER,
  NUMEROAUTORIZACION DECIMAL(12),
  NUMEROVALE DECIMAL(14),
  NUMERORECAP DECIMAL(14),
  NUMEROTARJETA VARCHAR(64),
  TARJETAENMASCARADA VARCHAR(24),
  HASHTARJETA VARCHAR(64),
  BIN DECIMAL(10),
  FECHAVALE TIMESTAMP,
  TIPOCREDITOARCHIVO VARCHAR(3),
  CODIGOTIPOCREDITO INTEGER,
  CODCATTIPTIPODOCUMENTO INTEGER,
  CODCATVALTIPODOCUMENTO VARCHAR(3),
  NUMEROCUOTA DECIMAL(2),
  CONSUMO DECIMAL(15,2),
  CONSUMOMASIVA DECIMAL(15,2),
  COMISION DECIMAL(15,2),
  VALORNETO DECIMAL(15,2),
  IVA DECIMAL(15,2),
  IVA0 DECIMAL(15,2),
  RETENCION DECIMAL(15,2),
  IVARETENCION DECIMAL(15,2),
  TOTALCUOTAS DECIMAL(2),
  VALORTOTAL DECIMAL(15,2),
  CAUSAL DECIMAL(2),
  CAUSAL1 DECIMAL(2),
  TIPOVALEARCHIVO DECIMAL(2),
  VALORPAGADO DECIMAL(15,2),
  NUMEROLOTE VARCHAR(20),
  COMPROBANTERETENCION VARCHAR(15),
  TIPOPAGO VARCHAR(3),
  TIPOREGISTRO VARCHAR(3),
  ESTADOPAGO VARCHAR(3),
  ERRORES VARCHAR(2000),
  OBSERVACION VARCHAR(2000),
  ESTADOREGISTROPAGO VARCHAR(3),
  USUARIOREGISTROPAGO VARCHAR(32) NOT NULL,
  FECHAREGISTROPAGO TIMESTAMP NOT NULL,
  USUARIOMODIFICACIONPAGO VARCHAR(32),
  FECHAMODIFICACIONPAGO TIMESTAMP,
  ESTADO VARCHAR(3),
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  IVACOMISION DECIMAL(15,2),
  AUTORIZACION VARCHAR(12),
  PRIMARY KEY (CODIGOBITACORAPAGO)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTBITVEN
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTBITVEN (
  CODIGOBITACORAVENTA DECIMAL(16) NOT NULL,
  CODIGOVENTA DECIMAL(16) NOT NULL,
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOCARGA DECIMAL(16),
  FECHATRANSACCIONCABECERA TIMESTAMP,
  FECHAPROCESOARCHIVO TIMESTAMP,
  NUMERORECAP VARCHAR(15),
  CODIGOESTABLECIMIENTO DECIMAL(15),
  FECHAULTIMOPAGO TIMESTAMP,
  NUMEROPAGOS DECIMAL(3),
  CODIGOVTC DECIMAL(18),
  MIGRADO VARCHAR(1),
  CODIGOPROCESADORAPAGO INTEGER,
  CODIGOLOCALARCHIVO INTEGER,
  CODIGOLOCAL INTEGER,
  CODIGOPROCESADORAARCHIVO VARCHAR(10),
  CODIGOPROCESADORA DECIMAL(10),
  NUMEROCUOTASRECAP DECIMAL(3),
  NUMEROVALE DECIMAL(14),
  FECHATRANSACCIONVALE TIMESTAMP,
  TIPOCREDITOARCHIVO VARCHAR(3),
  CODIGOTIPOCREDITO INTEGER,
  NUMEROCUOTAS DECIMAL(3),
  CODCATTIPPLAZO INTEGER,
  CODCATVALPLAZO VARCHAR(3),
  CODIGOTIPCRECOB DECIMAL(10),
  NUMEROTARJETA VARCHAR(64),
  TARJETAENMASCARADA VARCHAR(24),
  HASHTARJETA VARCHAR(64),
  BIN DECIMAL(10),
  NUMEROAUTORIZACION DECIMAL(12),
  VALORCONSUMO DECIMAL(15,2),
  VALORIVA DECIMAL(15,2),
  DESCONOCIDO VARCHAR(30),
  BASEIVA DECIMAL(10,2),
  BASEIVA0 DECIMAL(10,2),
  VALORNETO DECIMAL(15,2),
  VALORCOMISION DECIMAL(15,2),
  IVACOMISION DECIMAL(15,2),
  VALORCOBRO DECIMAL(15,2),
  PORCENTAJECOMISION DECIMAL(6,3),
  RETENCION DECIMAL(15,2),
  RETENCIONIVA DECIMAL(15,2),
  PORCENTAJERETENCION DECIMAL(6,3),
  PORCENTAJERETENCIONIVA DECIMAL(6,3),
  PORCENTAJEIVACOMISION DECIMAL(6,3),
  ESTADOVENTA VARCHAR(3),
  TOTALPAGADO DECIMAL(15,2),
  OBSERVACION VARCHAR(2000),
  ERRORES VARCHAR(2000),
  ESTADOREGISTROVENTA VARCHAR(3),
  USUARIOREGISTROVENTA VARCHAR(32) NOT NULL,
  FECHAREGISTROVENTA TIMESTAMP NOT NULL,
  USUARIOMODIFICACIONVENTA VARCHAR(32),
  FECHAMODIFICACIONVENTA TIMESTAMP,
  ESTADO VARCHAR(3),
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  AUTORIZACION VARCHAR(12),
  PRIMARY KEY (CODIGOBITACORAVENTA)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTCARGA
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTCARGA (
  CODIGOCARGA DECIMAL(16) NOT NULL,
  CODIGOCOMPANIA INTEGER NOT NULL,
  TIPO VARCHAR(3) NOT NULL,
  CODIGOLOCAL INTEGER,
  CODIGOPROCESADORA DECIMAL(10),
  FECHATRANSMISION TIMESTAMP,
  FECHAINICIO TIMESTAMP,
  FECHAFIN TIMESTAMP,
  URLORIGEN VARCHAR(500),
  NOMBREARCHIVO VARCHAR(200),
  FORMATOARCHIVO VARCHAR(3),
  UBICACIONARCHIVO VARCHAR(1000),
  CHECKSUMARCHIVO VARCHAR(64),
  ALGORITMOCHECKSUM VARCHAR(25),
  PESOARCHIVO DECIMAL(19),
  NUMEROLINEAS DECIMAL(10),
  VALORTOTAL DECIMAL(15,2),
  ESTADOCARGA VARCHAR(3),
  OBSERVACION VARCHAR(2000),
  ESTADO VARCHAR(3),
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  FECHAPAGO TIMESTAMP,
  PRIMARY KEY (CODIGOCARGA)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTCONAJUSTE
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTCONAJUSTE (
  CODIGOCONAJUSTE DECIMAL(16) NOT NULL,
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOPROCESADORA DECIMAL(10) NOT NULL,
  CODIGOCONPERIODO DECIMAL(16) NOT NULL,
  CODIGOLOCAL INTEGER,
  TIPOCREDITO VARCHAR(20),
  FECHAAJUSTE DATE,
  FECHACONTABLE DATE,
  FECHAPAGO DATE,
  IVARETENCION DECIMAL(15,2),
  RETENCION DECIMAL(15,2),
  VALORLIQUIDADO DECIMAL(15,2) NOT NULL,
  VALORPAGADO DECIMAL(15,2) NOT NULL,
  CONSUMO DECIMAL(15,2) NOT NULL,
  CONSUMOMASIVA DECIMAL(15,2) NOT NULL,
  COMISION DECIMAL(15,2) NOT NULL,
  IVA DECIMAL(15,2) NOT NULL,
  IVA0 DECIMAL(15,2) NOT NULL,
  VALORTOTAL DECIMAL(15,2) NOT NULL,
  VALORNETO DECIMAL(15,2) NOT NULL,
  ESTADO VARCHAR(3) NOT NULL,
  ESTADOAJUSTE VARCHAR(3) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  CODIGOCONEGRESO DECIMAL(16),
  ESTADOCONAJUSTETIPO INTEGER NOT NULL,
  ESTADOCONAJUSTEVALOR VARCHAR(3) NOT NULL,
  CODIGORECIBO DECIMAL(10),
  VALORCONTABLE DECIMAL(15,2),
  CODIGOCONPARAM DECIMAL(16),
  CARGAMANUAL SMALLINT,
  NUMEROFACTURA VARCHAR(30),
  PRIMARY KEY (CODIGOCONAJUSTE)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTCONBITPER
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTCONBITPER (
  CODIGOCONBITPERIODO DECIMAL(16) NOT NULL,
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOCONPERIODO DECIMAL(16) NOT NULL,
  FECHAINICIO DATE NOT NULL,
  FECHAFINAL DATE NOT NULL,
  ESTADOPERIODO VARCHAR(3) NOT NULL,
  ESTADOREGISTROPER VARCHAR(3),
  DIASGRACIA INTEGER,
  USUARIOREGISTROPER VARCHAR(32) NOT NULL,
  FECHAREGISTROPER TIMESTAMP NOT NULL,
  USUARIOMODIFICACIONPER VARCHAR(32),
  FECHAMODIFICACIONPER TIMESTAMP,
  CODIGOSISTEMA VARCHAR(10) NOT NULL,
  ESTADO VARCHAR(3) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  PRIMARY KEY (CODIGOCONBITPERIODO)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTCONCILIATION
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTCONCILIATION (
  CODE_CONCILIATION CHAR(36) NOT NULL,
  NAME_CONCILIATION VARCHAR(100),
  DESCRIPTION VARCHAR(200),
  ORDER_CONCILIATION INTEGER,
  COMPANY_CODE INTEGER NOT NULL,
  STATUS VARCHAR(1) NOT NULL,
  CREATED_BY_USER VARCHAR(50) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL,
  LAST_MODIFIED_BY_USER VARCHAR(50),
  LAST_MODIFIED_DATE TIMESTAMP,
  VERSION INTEGER NOT NULL,
  CREATED_FROM_IP VARCHAR(50) NOT NULL,
  UPDATED_FROM_IP VARCHAR(50),
  PRIMARY KEY (CODE_CONCILIATION)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTCONCRENOT
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTCONCRENOT (
  COMPANY_CODE INTEGER NOT NULL,
  TRACE BIGINT,
  HEADER_ID VARCHAR(30) NOT NULL,
  LOCAL_REFERENCE_CODE INTEGER NOT NULL,
  CLIENT_DOCUMENT_NUMBER VARCHAR(20) NOT NULL,
  CLIENT_CATALOG_TYPE INTEGER,
  CLIENT_CATALOG_CODE VARCHAR(3),
  DOCUMENT_NUMBER VARCHAR(50) NOT NULL,
  ACCESS_KEY VARCHAR(100) NOT NULL,
  TRANSACTION_DATE TIMESTAMP NOT NULL,
  ZERO_FEE DECIMAL(12,2),
  IVA_FEE DECIMAL(12,2),
  TRANSACTION_VALUE DECIMAL(12,2) NOT NULL,
  REFERENCED_DOCUMENT_NUMBER VARCHAR(50) NOT NULL,
  NOTE_NUMBER VARCHAR(20),
  SISTAR_CONSUMPTION_VALUE DECIMAL(12,2),
  SISTAR_CONSUMPTION_DATE TIMESTAMP,
  SISTAR_CONSUMPTION_STATUS_TYPE INTEGER,
  SISTAR_CONSUMPTION_STATUS VARCHAR(3),
  CREDIT_VALUE_STATUS CHAR(1) NOT NULL,
  OBSERVATIONS VARCHAR(1024),
  STATUS CHAR(1) NOT NULL,
  CREATED_BY_USER VARCHAR(50) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL,
  LAST_MODIFIED_BY_USER VARCHAR(50),
  LAST_MODIFIED_DATE TIMESTAMP,
  VERSION INTEGER NOT NULL,
  CREATED_FROM_IP VARCHAR(50) NOT NULL,
  UPDATED_FROM_IP VARCHAR(50),
  PRIMARY KEY (HEADER_ID)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTCONCRENOTLOG
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTCONCRENOTLOG (
  COMPANY_CODE INTEGER NOT NULL,
  HEADER_ID VARCHAR(30) NOT NULL,
  OBSERVATIONS VARCHAR(2048),
  STATUS CHAR(1) NOT NULL,
  CREATED_BY_USER VARCHAR(50) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL,
  LAST_MODIFIED_BY_USER VARCHAR(50),
  LAST_MODIFIED_DATE TIMESTAMP,
  VERSION INTEGER NOT NULL,
  CREATED_FROM_IP VARCHAR(50) NOT NULL,
  UPDATED_FROM_IP VARCHAR(50),
  PRIMARY KEY (HEADER_ID)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTCONEGRESO
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTCONEGRESO (
  CODIGOCONEGRESO DECIMAL(16) NOT NULL,
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOPROCESADORA DECIMAL(10) NOT NULL,
  CODIGOLOCAL INTEGER NOT NULL,
  TIPOCREDITO VARCHAR(20) NOT NULL,
  FECHAPAGO DATE NOT NULL,
  FECHACONTABLE DATE NOT NULL,
  RETENCION DECIMAL(15,2),
  IVARETENCION DECIMAL(15,2),
  VALORLIQUIDADO DECIMAL(15,2) NOT NULL,
  VALORPAGADO DECIMAL(15,2) NOT NULL,
  CONSUMO DECIMAL(15,2) NOT NULL,
  CONSUMOMASIVA DECIMAL(15,2) NOT NULL,
  COMISION DECIMAL(15,2) NOT NULL,
  IVA DECIMAL(15,2) NOT NULL,
  IVA0 DECIMAL(15,2) NOT NULL,
  VALORTOTAL DECIMAL(15,2) NOT NULL,
  VALORNETO DECIMAL(15,2) NOT NULL,
  OBSERVACION VARCHAR(2000),
  ESTADO VARCHAR(3) NOT NULL,
  ESTADOEGRESO VARCHAR(3) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  CODIGOCONPARAM DECIMAL(16),
  CODIGOCONPERIODO DECIMAL(16) NOT NULL,
  EXCEDENTE DECIMAL(15,2),
  CODIGOCONINGRESO DECIMAL(16) NOT NULL,
  VALORCONTABLE DECIMAL(15,2),
  CODIGORECIBO DECIMAL(10),
  CARGAMANUAL SMALLINT,
  SALDOCONTABLE DECIMAL(15,2) NOT NULL,
  ESTADOCONEGRESOTIPO INTEGER NOT NULL,
  ESTADOCONEGRESOVALOR VARCHAR(3) NOT NULL,
  CODIGOCONEGRESOPADRE DECIMAL(16),
  NUMEROVALE DECIMAL(14),
  OTRASCUENTAS SMALLINT,
  PRIMARY KEY (CODIGOCONEGRESO)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTCONEGRESODETALLE
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTCONEGRESODETALLE (
  CODIGOCONEGRESODETALLE DECIMAL(16) NOT NULL,
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOPAGO DECIMAL(16) NOT NULL,
  ESTADO VARCHAR(3) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  CODIGOCONEGRESO DECIMAL(16),
  CODIGOCONAJUSTE DECIMAL(16),
  PRIMARY KEY (CODIGOCONEGRESODETALLE)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTCONINGRESO
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTCONINGRESO (
  CODIGOCONINGRESO DECIMAL(16) NOT NULL,
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOPROCESADORA DECIMAL(10) NOT NULL,
  CODIGOLOCAL INTEGER NOT NULL,
  TIPOCREDITO VARCHAR(20) NOT NULL,
  FECHAVENTA DATE NOT NULL,
  FECHACONTABLE DATE NOT NULL,
  VALORCOMISION DECIMAL(15,2) NOT NULL,
  IVACOMISION DECIMAL(15,2) NOT NULL,
  VALORNETO DECIMAL(15,2) NOT NULL,
  BASEIVA12 DECIMAL(15,2) NOT NULL,
  BASEIVA0 DECIMAL(15,2) NOT NULL,
  VALORCONSUMO DECIMAL(15,2) NOT NULL,
  VALORIVA DECIMAL(15,2) NOT NULL,
  RETENCION DECIMAL(15,2) NOT NULL,
  RETENCIONIVA DECIMAL(15,2) NOT NULL,
  VALORCOBRO DECIMAL(15,2) NOT NULL,
  OBSERVACION VARCHAR(2000),
  ESTADOINGRESO VARCHAR(3) NOT NULL,
  ESTADO VARCHAR(3) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  CODIGOCONPARAM DECIMAL(16),
  CODIGOCONPERIODO DECIMAL(16) NOT NULL,
  NUMEROFACTURA VARCHAR(30),
  SALDOCONTABLE DECIMAL(15,2) NOT NULL,
  VALORCONTABLE DECIMAL(15,2),
  TIPOCAPTURA VARCHAR(20),
  CODIGOCONINGRESOPADRE DECIMAL(16),
  PRIMARY KEY (CODIGOCONINGRESO)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTCONINGRESODETALLE
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTCONINGRESODETALLE (
  CODIGOCONINGRESODETALLE DECIMAL(16) NOT NULL,
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOVENTA DECIMAL(16),
  ESTADO VARCHAR(3) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  CODIGOCONINGRESO DECIMAL(16) NOT NULL,
  FECHAMODIFICACION TIMESTAMP,
  PRIMARY KEY (CODIGOCONINGRESODETALLE)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTCONPARAM
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTCONPARAM (
  CODIGOCONPARAM DECIMAL(16) NOT NULL,
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOINSTITUCIONTARJETA DECIMAL(10) NOT NULL,
  TIPOCREDITO VARCHAR(20) NOT NULL,
  CUENTAPUENTE VARCHAR(20) NOT NULL,
  CUENTAIVA VARCHAR(20) NOT NULL,
  CUENTACOMISION VARCHAR(20) NOT NULL,
  CUENTABANCO VARCHAR(20) NOT NULL,
  CUENTAFALLAS VARCHAR(20) NOT NULL,
  CUENTARETENCION VARCHAR(20) NOT NULL,
  CUENTARETENCIONIVA VARCHAR(20) NOT NULL,
  TIPODOCUMENTO VARCHAR(20) NOT NULL,
  AREAFISCALSINIVA VARCHAR(20) NOT NULL,
  AREAFISCALIVA VARCHAR(20) NOT NULL,
  UNIDADNEGOCIO VARCHAR(20),
  ICA VARCHAR(20) NOT NULL,
  ESTADO VARCHAR(20) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  PRIMARY KEY (CODIGOCONPARAM)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTCONPERIODO
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTCONPERIODO (
  CODIGOCONPERIODO DECIMAL(16) NOT NULL,
  CODIGOCOMPANIA INTEGER NOT NULL,
  FECHAINICIO DATE NOT NULL,
  FECHAFINAL DATE NOT NULL,
  DIASGRACIA INTEGER NOT NULL,
  ESTADO VARCHAR(3) NOT NULL,
  ESTADOPERIODO VARCHAR(3) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  CODIGOSISTEMA VARCHAR(10) NOT NULL,
  PERIODOANTERIOR DECIMAL(16),
  PRIMARY KEY (CODIGOCONPERIODO)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTCRICON
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTCRICON (
  CODE_CRICON CHAR(36) NOT NULL,
  CODE_CONCILIATION CHAR(36),
  PARAMETER_CRICON CHAR(36),
  COMPARATOR_OPERATOR_TYPE INTEGER,
  COMPARATOR_OPERATOR_VALUE VARCHAR(3),
  VALUE_CRICON VARCHAR(100),
  LOGIC_OPERATOR_TYPE INTEGER,
  LOGIC_OPERATOR_VALUE VARCHAR(3),
  COMPANY_CODE INTEGER NOT NULL,
  STATUS VARCHAR(1) NOT NULL,
  CREATED_BY_USER VARCHAR(50) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL,
  LAST_MODIFIED_BY_USER VARCHAR(50),
  LAST_MODIFIED_DATE TIMESTAMP,
  VERSION INTEGER NOT NULL,
  CREATED_FROM_IP VARCHAR(50) NOT NULL,
  UPDATED_FROM_IP VARCHAR(50),
  PRIMARY KEY (CODE_CRICON)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTCUOPAG
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTCUOPAG (
  CODIGOCUOPAG DECIMAL(18) NOT NULL,
  CODIGOCUOTA DECIMAL(18) NOT NULL,
  CODIGOPAGO DECIMAL(16),
  ESTADO VARCHAR(3),
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  CODIGOCONCILIACION CHAR(36),
  PRIMARY KEY (CODIGOCUOPAG)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTCUOPORCOB
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTCUOPORCOB (
  CODIGOCUOPORCOB DECIMAL(16) NOT NULL,
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOLOCAL INTEGER,
  NOMBRELOCAL VARCHAR(100) NOT NULL,
  CODIGOREFERENCIALOCAL INTEGER,
  NOMBREPROCESADORA VARCHAR(100) NOT NULL,
  CODIGOPROCESADORA DECIMAL(10) NOT NULL,
  NOMBRETIPOCREDITO VARCHAR(250) NOT NULL,
  FECHAVENTA TIMESTAMP,
  VALORACTUAL DECIMAL(15,2),
  VALORMAYOR31MENOR60 DECIMAL(15,2),
  VALORMAYOR61MENOR90 DECIMAL(15,2),
  VALORMAYOR91MENOR150 DECIMAL(15,2),
  VALORMAYOR151MENOR360 DECIMAL(15,2),
  VALORMAYOR360 DECIMAL(15,2),
  ESTADO VARCHAR(3) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  CODIGOTIPOCREDITO INTEGER,
  PRIMARY KEY (CODIGOCUOPORCOB)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTCUOPORCOB_TEST
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTCUOPORCOB_TEST (
  CODIGOCUOPORCOB DECIMAL(16) NOT NULL,
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOLOCAL INTEGER,
  NOMBRELOCAL VARCHAR(100) NOT NULL,
  CODIGOREFERENCIALOCAL INTEGER,
  NOMBREPROCESADORA VARCHAR(100) NOT NULL,
  CODIGOPROCESADORA DECIMAL(10) NOT NULL,
  NOMBRETIPOCREDITO VARCHAR(250) NOT NULL,
  FECHAVENTA TIMESTAMP,
  VALORACTUAL DECIMAL(15,2),
  VALORMAYOR31MENOR60 DECIMAL(15,2),
  VALORMAYOR61MENOR90 DECIMAL(15,2),
  VALORMAYOR91MENOR150 DECIMAL(15,2),
  VALORMAYOR151MENOR360 DECIMAL(15,2),
  VALORMAYOR360 DECIMAL(15,2),
  ESTADO VARCHAR(3) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  CODIGOTIPOCREDITO INTEGER
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTCUOPORRECAP
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTCUOPORRECAP (
  CODIGOCUOPORCOB DECIMAL(16) NOT NULL,
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOLOCAL INTEGER,
  NOMBRELOCAL VARCHAR(100) NOT NULL,
  CODIGOREFERENCIALOCAL INTEGER,
  NOMBREPROCESADORA VARCHAR(100) NOT NULL,
  CODIGOPROCESADORA DECIMAL(10) NOT NULL,
  NOMBRETIPOCREDITO VARCHAR(250) NOT NULL,
  FECHAVENTA TIMESTAMP,
  VALORACTUAL DECIMAL(15,2),
  VALORMAYOR31MENOR60 DECIMAL(15,2),
  VALORMAYOR61MENOR90 DECIMAL(15,2),
  VALORMAYOR91MENOR150 DECIMAL(15,2),
  VALORMAYOR151MENOR360 DECIMAL(15,2),
  VALORMAYOR360 DECIMAL(15,2),
  ESTADO VARCHAR(3) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  CODIGOTIPOCREDITO INTEGER,
  NUMERORECAP VARCHAR(15) NOT NULL,
  PRIMARY KEY (CODIGOCUOPORCOB)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTCUOTA
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTCUOTA (
  CODIGOCUOTA DECIMAL(18) NOT NULL,
  CODIGOVENTA DECIMAL(16),
  NUMEROCUOTA DECIMAL(3) NOT NULL,
  VALORESTIMADO DECIMAL(15,2),
  FECHAESTIMADACOBRO TIMESTAMP,
  FECHAPROCESADORA TIMESTAMP,
  VALORREAL DECIMAL(15,2),
  FECHAREALCOBRO TIMESTAMP,
  ESTADOCUOTA VARCHAR(3),
  ESTADO VARCHAR(3),
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  OBSERVACION VARCHAR(350),
  PRIMARY KEY (CODIGOCUOTA)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTCUOTASERVICIO
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTCUOTASERVICIO (
  CODIGOCUOTASERVICIO DECIMAL(18) NOT NULL,
  VALOR DECIMAL(15,2) NOT NULL,
  NUMEROCUOTA DECIMAL(3) NOT NULL,
  CODIGOVENTASERVICIO DECIMAL(18) NOT NULL,
  ESTADO VARCHAR(3),
  ESTADOCUOTA VARCHAR(3),
  FECHAESTIMADAPAGO TIMESTAMP,
  VALORREAL DECIMAL(15,2),
  FECHAREALCOBRO TIMESTAMP,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  PRIMARY KEY (CODIGOCUOTASERVICIO)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTDETCONVENPAG
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTDETCONVENPAG (
  CODIGODETCONVENPAG DECIMAL(18) NOT NULL,
  CODIGOCUOTASERVICIO DECIMAL(18) NOT NULL,
  CODIGOPAGOSERVICIO DECIMAL(18) NOT NULL,
  ESTADO VARCHAR(3),
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  PRIMARY KEY (CODIGODETCONVENPAG)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTDETFRECOB
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTDETFRECOB (
  CODIGODETFRECOB DECIMAL(10) NOT NULL,
  CODIGOFRECOB DECIMAL(10) NOT NULL,
  CODCATTIPUNITIEVENTA INTEGER NOT NULL,
  CODCATVALUNITIEVENTA VARCHAR(3) NOT NULL,
  VALORFIJOINICIALVENTA VARCHAR(20),
  VALORFIJOFINALVENTA VARCHAR(20),
  CODIGOVALORTIEMPOINICIALVENTA INTEGER,
  CODIGOVALORTIEMPOFINALVENTA INTEGER,
  DESCRIPCIONVENTA VARCHAR(1000),
  CODCATTIPUNITIEPAGO INTEGER NOT NULL,
  CODCATVALUNITIEPAGO VARCHAR(3) NOT NULL,
  VALORFIJOPAGO VARCHAR(20),
  CODIGOVALORTIEMPOPAGO INTEGER,
  CODCATTIPUNITIEAJUPAGO INTEGER,
  CODCATVALUNITIEAJUPAGO VARCHAR(3),
  VALORAJUSTEPAGO INTEGER,
  DESCRIPCIONPAGO VARCHAR(1000),
  CODCATTIPUNITIEGRACIA INTEGER,
  CODCATVALUNITIEGRACIA VARCHAR(3),
  GRACIA INTEGER,
  ESTADO VARCHAR(3) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  PRIMARY KEY (CODIGODETFRECOB)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTDETREC
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTDETREC (
  CODIGODETREC DECIMAL(10) NOT NULL,
  CODIGOINSTITUCIONTARJETA DECIMAL(10) NOT NULL,
  CODIGORECIBO DECIMAL(10) NOT NULL,
  CONSUMO DECIMAL(15,2),
  PORCENTAJECOMISION DECIMAL(15,2),
  BASECOMISION DECIMAL(15,2),
  IVACOMISION DECIMAL(15,2),
  VALORCOMISION DECIMAL(15,2),
  PORCENTAJERETENCION DECIMAL(15,2),
  IVARETENCION DECIMAL(15,2),
  TOTAL DECIMAL(15,2),
  IVA DECIMAL(15,2),
  ICE DECIMAL(15,2),
  VENTASMENOSIVA DECIMAL(15,2),
  VENTASMENOSICE DECIMAL(15,2),
  VALORBRUTO DECIMAL(15,2),
  VALOR DECIMAL(15,2),
  RETENCION DECIMAL(15,2),
  ESTADO VARCHAR(3) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  CODIGOTIPOCREDITO INTEGER,
  CODIGOCOMPANIA INTEGER,
  CODIGOESTABLECIMIENTO INTEGER,
  PRIMARY KEY (CODIGODETREC)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTDOCASIG
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTDOCASIG (
  CODIGODOCASIG DECIMAL(10) NOT NULL,
  CODIGOFACTURA DECIMAL(15),
  CODIGOINSTITUCIONTARJETA DECIMAL(10) NOT NULL,
  CODIGONOTACREDITO DECIMAL(10),
  CODIGORECIBO DECIMAL(10) NOT NULL,
  TOTAL DECIMAL(15,2),
  USUARIOCREACION VARCHAR(32) NOT NULL,
  OBSERVACION VARCHAR(2000),
  CODIGOCOMPANIA INTEGER,
  ESTADO VARCHAR(3) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  PRIMARY KEY (CODIGODOCASIG)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTDOCUMENTO
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTDOCUMENTO (
  CODIGODOCUMENTO DECIMAL(16) NOT NULL,
  NOMBREDOCUMENTO VARCHAR(100),
  DESCRIPCION VARCHAR(400),
  MIMETYPE VARCHAR(64),
  ARCHIVO BLOB NOT NULL,
  ESTADO VARCHAR(3) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  PRIMARY KEY (CODIGODOCUMENTO)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTESTCUENTA
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTESTCUENTA (
  CODIGOESTADOCUENTA DECIMAL(16) NOT NULL,
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOINSTITUCIONTARJETA DECIMAL(10) NOT NULL,
  CODIGOCONPERIODO DECIMAL(16) NOT NULL,
  VALORINICIAL DECIMAL(15,2),
  VALORFINAL DECIMAL(15,2),
  TOTALVENTAS DECIMAL(15,2),
  TOTALPAGOS DECIMAL(15,2),
  CREDITOAJUSTE DECIMAL(15,2),
  DEBITOAJUSTE DECIMAL(15,2),
  ESTADO VARCHAR(3) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  PRIMARY KEY (CODIGOESTADOCUENTA)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTETIQUETA
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTETIQUETA (
  CODIGOETIQUETA DECIMAL(16) NOT NULL,
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOREFERENCIA VARCHAR(16),
  NOMBRE VARCHAR(32) NOT NULL,
  OBSERVACION VARCHAR(100),
  PAGINATIPO INTEGER NOT NULL,
  PAGINAVALOR VARCHAR(3) NOT NULL,
  ETIQUETATIPO INTEGER NOT NULL,
  ETIQUETAVALOR VARCHAR(3) NOT NULL,
  ESTADO VARCHAR(3) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  PRIMARY KEY (CODIGOETIQUETA)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTFRECOB
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTFRECOB (
  CODIGOFRECOB DECIMAL(10) NOT NULL,
  CODIGOCOMPANIA INTEGER NOT NULL,
  NOMBRE VARCHAR(250) NOT NULL,
  DESCRIPCION VARCHAR(1000),
  ESTADO VARCHAR(3) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  TIPO CHAR(3) NOT NULL,
  PRIMARY KEY (CODIGOFRECOB)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTLOCALDETALLE
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTLOCALDETALLE (
  CODIGODETALLE INTEGER NOT NULL,
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOAREATRABAJO INTEGER NOT NULL,
  CODCATTIPESTADOLOCAL INTEGER,
  CODCATVALESTADOLOCAL VARCHAR(3),
  FECHADESDE TIMESTAMP,
  FECHAHASTA TIMESTAMP,
  OBSERVACION VARCHAR(2000),
  ESTADO VARCHAR(3) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  ESTADOPINPAD VARCHAR(3),
  ZONALOCAL VARCHAR(3),
  PRIMARY KEY (CODIGODETALLE)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTMAPDAT
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTMAPDAT (
  CODE_MAPDAT CHAR(36) NOT NULL,
  CODE_CONCILIATION CHAR(36),
  PAY_ATTRIBUTE CHAR(36),
  SALE_ATTRIBUTE CHAR(36),
  COMPANY_CODE INTEGER NOT NULL,
  STATUS VARCHAR(1) NOT NULL,
  CREATED_BY_USER VARCHAR(50) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL,
  LAST_MODIFIED_BY_USER VARCHAR(50),
  LAST_MODIFIED_DATE TIMESTAMP,
  VERSION INTEGER NOT NULL,
  CREATED_FROM_IP VARCHAR(50) NOT NULL,
  UPDATED_FROM_IP VARCHAR(50),
  USETOCONCILIATION SMALLINT NOT NULL,
  PRIMARY KEY (CODE_MAPDAT)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTNOTACREDITO
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTNOTACREDITO (
  CODIGONOTACREDITO DECIMAL(10) NOT NULL,
  CODIGOCOMPANIA INTEGER NOT NULL,
  VALORNOTACREDITO DECIMAL(15,2) NOT NULL,
  VALORRETENCION DECIMAL(15,2),
  FECHAPAGO TIMESTAMP NOT NULL,
  OBSERVACION VARCHAR(1000),
  ESTADO VARCHAR(3) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  CODIGOPROCESADORA DECIMAL(10),
  PRIMARY KEY (CODIGOCOMPANIA, CODIGONOTACREDITO)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTORIPARMAP
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTORIPARMAP (
  CODE_ORIPARMAP CHAR(36) NOT NULL,
  PARAMETER_ORIPARMAP VARCHAR(100),
  NAME_ORIPARMAP VARCHAR(100),
  DATA_TYPE VARCHAR(50),
  DESCRIPTION VARCHAR(200),
  ORIGEN_TYPE INTEGER,
  ORIGEN_VALUE VARCHAR(3),
  COMPANY_CODE INTEGER NOT NULL,
  STATUS VARCHAR(1) NOT NULL,
  CREATED_BY_USER VARCHAR(50) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL,
  LAST_MODIFIED_BY_USER VARCHAR(50),
  LAST_MODIFIED_DATE TIMESTAMP,
  VERSION INTEGER NOT NULL,
  CREATED_FROM_IP VARCHAR(50) NOT NULL,
  UPDATED_FROM_IP VARCHAR(50),
  PRIMARY KEY (CODE_ORIPARMAP)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTPAGO
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTPAGO (
  CODIGOPAGO DECIMAL(16) NOT NULL,
  CODIGOCARGA DECIMAL(16),
  CODIGOCOMPANIA INTEGER NOT NULL,
  CIUDADEMISION VARCHAR(3),
  FECHAPROCESODATOS TIMESTAMP,
  CODIGOPROCESADORAARCHIVO VARCHAR(5),
  CODIGOPROCESADORA DECIMAL(10),
  NOMBREPROCESADORA VARCHAR(50),
  MONEDA VARCHAR(5),
  NUMEROVALEGENERADO DECIMAL(14),
  NUMERORECAPGENERADO DECIMAL(14),
  VALORLIQUIDADO DECIMAL(15,2),
  REFERENCIATRANSFERENCIA VARCHAR(20),
  TIPODOCUMENTOARCHIVO DECIMAL(5),
  TIPOCREDITOVENTAARCHIVO DECIMAL(5),
  CODIGOVTC DECIMAL(18),
  MIGRADO VARCHAR(1),
  FECHAPAGO TIMESTAMP,
  CODIGOESTABLECIMIENTO VARCHAR(32),
  CODIGOLOCAL INTEGER,
  NUMEROAUTORIZACION DECIMAL(12),
  NUMEROVALE DECIMAL(14),
  NUMERORECAP DECIMAL(14),
  NUMEROTARJETA VARCHAR(64),
  TARJETAENMASCARADA VARCHAR(24),
  HASHTARJETA VARCHAR(64),
  BIN DECIMAL(10),
  FECHAVALE TIMESTAMP,
  TIPOCREDITOARCHIVO VARCHAR(3),
  CODIGOTIPOCREDITO INTEGER,
  CODCATTIPTIPODOCUMENTO INTEGER,
  CODCATVALTIPODOCUMENTO VARCHAR(3),
  NUMEROCUOTA DECIMAL(2),
  CONSUMO DECIMAL(15,2),
  CONSUMOMASIVA DECIMAL(15,2),
  COMISION DECIMAL(15,2),
  VALORNETO DECIMAL(15,2),
  IVA DECIMAL(15,2),
  IVA0 DECIMAL(15,2),
  RETENCION DECIMAL(15,2),
  IVARETENCION DECIMAL(15,2),
  TOTALCUOTAS DECIMAL(2),
  VALORTOTAL DECIMAL(15,2),
  CAUSAL DECIMAL(2),
  CAUSAL1 DECIMAL(2),
  TIPOVALEARCHIVO DECIMAL(2),
  VALORPAGADO DECIMAL(15,2),
  NUMEROLOTE VARCHAR(20),
  COMPROBANTERETENCION VARCHAR(15),
  TIPOPAGO VARCHAR(3),
  TIPOREGISTRO VARCHAR(3),
  ESTADOPAGO VARCHAR(3),
  ERRORES VARCHAR(2000),
  OBSERVACION VARCHAR(2000),
  ESTADO VARCHAR(3),
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  IVACOMISION DECIMAL(15,2),
  AUTORIZACION VARCHAR(12),
  ESTADOTRANSMISION VARCHAR(3),
  PRIMARY KEY (CODIGOPAGO)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTPAGOSERVICIO
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTPAGOSERVICIO (
  CODIGOPAGOSERVICIO DECIMAL(18) NOT NULL,
  CODIGOPRODUCTO DECIMAL(18),
  AUTORIZACION VARCHAR(50),
  IDENTIFICADOR VARCHAR(50) NOT NULL,
  VALOR DECIMAL(15,2) NOT NULL,
  CODIGOPRODUCTOARCHIVO VARCHAR(10),
  FECHAPAGO TIMESTAMP,
  FECHAVENTA TIMESTAMP,
  OBSERVACION VARCHAR(255),
  ESTADOPAGO VARCHAR(3),
  CODIGOCARGA DECIMAL(16),
  NUMEROCUOTA DECIMAL(3),
  ERRORES VARCHAR(255),
  CODIGOLOCAL INTEGER,
  CODIGOLOCALARCHIVO INTEGER,
  CODIGOCOMPANIA INTEGER,
  ESTADO VARCHAR(3),
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  PRIMARY KEY (CODIGOPAGOSERVICIO)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTPARAMETRO
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTPARAMETRO (
  CODIGOPARAMETRO VARCHAR(25) NOT NULL,
  DESCRIPCIONPARAMETRO VARCHAR(256) NOT NULL,
  VALORPARAMETRO VARCHAR(1000) NOT NULL,
  IDSISTEMA VARCHAR(10),
  ESTADO VARCHAR(3),
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  ALCANCETIPO INTEGER,
  ALCANCEVALOR VARCHAR(3),
  PRIMARY KEY (CODIGOPARAMETRO)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTPRODUCTO
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTPRODUCTO (
  CODIGOPRODUCTO DECIMAL(18) NOT NULL,
  CODIGOREFERENCIAPRODUCTO VARCHAR(20) NOT NULL,
  NOMBRE VARCHAR(1000) NOT NULL,
  CODIGOTIPOSERVICIO INTEGER,
  CODIGOVALORSERVICIO VARCHAR(3),
  CODIGOOPERADORA DECIMAL(10) NOT NULL,
  ETIQUETA VARCHAR(25),
  ESTADO VARCHAR(3),
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  PRIMARY KEY (CODIGOPRODUCTO)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTRECIBO
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTRECIBO (
  CODIGORECIBO DECIMAL(10) NOT NULL,
  FECHAPAGO TIMESTAMP NOT NULL,
  GRUPO DECIMAL(10),
  TOTAL DECIMAL(15,2) NOT NULL,
  ESTADORECIBOTIPO INTEGER NOT NULL,
  ESTADORECIBOVALOR VARCHAR(3) NOT NULL,
  OBSERVACION VARCHAR(2000),
  SERIETARJETAS DECIMAL(10),
  SERIESERVICIOS DECIMAL(10),
  TIPORECIBO VARCHAR(3) NOT NULL,
  ESTADO VARCHAR(3) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  DIFERENCIA DECIMAL(15,2),
  TOTALNOTASCREDITO DECIMAL(15,2),
  TOTALDETALLE DECIMAL(15,2),
  PRIMARY KEY (CODIGORECIBO)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTREGARC
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTREGARC (
  CODIGOREGARC DECIMAL(16) NOT NULL,
  CODIGOCARGA DECIMAL(16) NOT NULL,
  NUMEROLINEA DECIMAL(10),
  CONTENIDO VARCHAR(2000),
  ESTADOREGISTRO VARCHAR(3),
  OBSERVACION VARCHAR(2000),
  ESTADO VARCHAR(3),
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  PRIMARY KEY (CODIGOREGARC)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTREGCOM
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTREGCOM (
  CODIGOREGCOM DECIMAL(10) NOT NULL,
  CODIGOOPERADORA DECIMAL(10),
  CODCATTIPSERVICIO INTEGER,
  CODCATVALSERVICIO VARCHAR(3),
  CODIGOPROSER DECIMAL(18),
  CODCATTIPUNITIE INTEGER,
  CODCATVALUNITIE VARCHAR(3),
  VALTIEINI VARCHAR(20),
  VALTIEFIN VARCHAR(20),
  VALMONINI DECIMAL(15,2),
  VALMONFIN DECIMAL(15,2),
  COMVALMON VARCHAR(3),
  PORCOM DECIMAL(6,4),
  PORICE DECIMAL(6,3),
  FECHAINICIO TIMESTAMP,
  FECHAFIN TIMESTAMP,
  ESTADO VARCHAR(3) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  PRIMARY KEY (CODIGOREGCOM)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTRELCARFAC
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTRELCARFAC (
  CODIGORELCARFAC DECIMAL(18) NOT NULL,
  CODIGOFACTURA DECIMAL(15) NOT NULL,
  CODIGOCARGA DECIMAL(16),
  CODIGOCOMPANIA INTEGER,
  OBSERVACION VARCHAR(2000),
  ESTADO VARCHAR(3),
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  PRIMARY KEY (CODIGORELCARFAC)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTRELCARNOTCRE
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTRELCARNOTCRE (
  CODIGORELCARNOTACRE DECIMAL(10) NOT NULL,
  CODIGOCARGA DECIMAL(16) NOT NULL,
  CODIGONOTACREDITO DECIMAL(10) NOT NULL,
  CODIGOCOMPANIA INTEGER NOT NULL,
  ESTADO VARCHAR(3) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  PRIMARY KEY (CODIGOCOMPANIA, CODIGORELCARNOTACRE)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTRELPAGNOTCRE
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTRELPAGNOTCRE (
  CODIGORELPAGNOTACRE DECIMAL(16) NOT NULL,
  CODIGOPAGO DECIMAL(16) NOT NULL,
  CODIGONOTACREDITO DECIMAL(10) NOT NULL,
  CODIGOCOMPANIA INTEGER NOT NULL,
  ESTADO VARCHAR(3) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  PRIMARY KEY (CODIGOCOMPANIA, CODIGORELPAGNOTACRE)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTTIPCRE
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTTIPCRE (
  CODIGOTIPCRE INTEGER NOT NULL,
  CODIGOCOMPANIA INTEGER NOT NULL,
  NOMBRE VARCHAR(250) NOT NULL,
  CODIGOREFERENCIA VARCHAR(6) NOT NULL,
  ESTADO VARCHAR(3) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  CLASE VARCHAR(3),
  PRIMARY KEY (CODIGOTIPCRE)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTTIPCRECOB
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTTIPCRECOB (
  CODIGOTIPCRECOB DECIMAL(10) NOT NULL,
  CODIGOTIPCRECOBPADRE DECIMAL(10),
  CODIGOPROCESADORA DECIMAL(10) NOT NULL,
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOFORMATO INTEGER,
  CODIGOLOCAL INTEGER,
  CODIGOTIPOCREDITO INTEGER NOT NULL,
  CODCATTIPPLAZOVENTA INTEGER,
  CODCATVALPLAZOVENTA VARCHAR(3),
  COMISION DECIMAL(15,6) NOT NULL,
  RETENCIONFUENTE DECIMAL(15,6) NOT NULL,
  RETENCIONIVACONSUMO DECIMAL(15,6) NOT NULL,
  CODIGOFRECOB DECIMAL(10) NOT NULL,
  CODCATTIPDESCOMRET INTEGER,
  CODCATVALDESCOMRET VARCHAR(3),
  CODCATTIPPLAZOPAGO INTEGER,
  CODCATVALPLAZOPAGO VARCHAR(3),
  CODCATTIPUNITIEGRACIA INTEGER,
  CODCATVALUNITIEGRACIA VARCHAR(3),
  GRACIA INTEGER,
  TOLERANCIA DECIMAL(15,6),
  FECHADESDE TIMESTAMP NOT NULL,
  FECHAHASTA TIMESTAMP,
  ESTADO VARCHAR(3) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  REGDIALAB VARCHAR(3),
  APLIVACOM VARCHAR(1),
  TOLERANCIAMONTO DECIMAL(15,2) NOT NULL,
  PRIMARY KEY (CODIGOTIPCRECOB)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTVALTIEMPO
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTVALTIEMPO (
  CODIGOVALTIEMPO INTEGER NOT NULL,
  CODIGOVALTIEMPOPADRE INTEGER,
  NOMBRE VARCHAR(100) NOT NULL,
  DESCRIPCION VARCHAR(200),
  VALOR VARCHAR(10),
  ESTADO VARCHAR(3) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  PRIMARY KEY (CODIGOVALTIEMPO)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTVENTA
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTVENTA (
  CODIGOVENTA DECIMAL(16) NOT NULL,
  CODIGOCOMPANIA INTEGER NOT NULL,
  CODIGOCARGA DECIMAL(16),
  FECHATRANSACCIONCABECERA TIMESTAMP,
  FECHAPROCESOARCHIVO TIMESTAMP,
  NUMERORECAP VARCHAR(15),
  CODIGOESTABLECIMIENTO DECIMAL(15),
  FECHAULTIMOPAGO TIMESTAMP,
  NUMEROPAGOS DECIMAL(3),
  CODIGOVTC DECIMAL(18),
  MIGRADO VARCHAR(1),
  CODIGOPROCESADORAPAGO INTEGER,
  CODIGOLOCALARCHIVO INTEGER,
  CODIGOLOCAL INTEGER,
  CODIGOPROCESADORAARCHIVO VARCHAR(10),
  CODIGOPROCESADORA DECIMAL(10),
  NUMEROCUOTASRECAP DECIMAL(3),
  NUMEROVALE DECIMAL(14),
  FECHATRANSACCIONVALE TIMESTAMP,
  TIPOCREDITOARCHIVO VARCHAR(5),
  CODIGOTIPOCREDITO INTEGER,
  NUMEROCUOTAS DECIMAL(3),
  CODCATTIPPLAZO INTEGER,
  CODCATVALPLAZO VARCHAR(3),
  CODIGOTIPCRECOB DECIMAL(10),
  NUMEROTARJETA VARCHAR(64),
  TARJETAENMASCARADA VARCHAR(24),
  HASHTARJETA VARCHAR(64),
  BIN DECIMAL(10),
  NUMEROAUTORIZACION DECIMAL(12),
  VALORCONSUMO DECIMAL(15,2),
  VALORIVA DECIMAL(15,2),
  DESCONOCIDO VARCHAR(30),
  BASEIVA DECIMAL(10,2),
  BASEIVA0 DECIMAL(10,2),
  VALORNETO DECIMAL(15,2),
  VALORCOMISION DECIMAL(15,2),
  IVACOMISION DECIMAL(15,2),
  VALORCOBRO DECIMAL(15,2),
  PORCENTAJECOMISION DECIMAL(6,3),
  RETENCION DECIMAL(15,2),
  RETENCIONIVA DECIMAL(15,2),
  PORCENTAJERETENCION DECIMAL(6,3),
  PORCENTAJERETENCIONIVA DECIMAL(6,3),
  PORCENTAJEIVACOMISION DECIMAL(6,3),
  ESTADOVENTA VARCHAR(3),
  TOTALPAGADO DECIMAL(15,2),
  OBSERVACION VARCHAR(2000),
  ERRORES VARCHAR(2000),
  ESTADO VARCHAR(3),
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  AUTORIZACION VARCHAR(12),
  ESTADOTRANSMISION VARCHAR(3),
  FECHAEXTEMPORANEA DATE,
  PRIMARY KEY (CODIGOVENTA)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTVENTAETIQUETA
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTVENTAETIQUETA (
  CODIGOVENTAETIQUETA DECIMAL(16) NOT NULL,
  CODIGOETIQUETA DECIMAL(16) NOT NULL,
  CODIGOVENTA DECIMAL(16) NOT NULL,
  ESTADO VARCHAR(3) NOT NULL,
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  PRIMARY KEY (CODIGOVENTAETIQUETA)
);

-- ============================================================
-- TABLE: SMXFINANC.SFSCTTVENTASERVICIO
-- ============================================================
CREATE TABLE SMXFINANC.SFSCTTVENTASERVICIO (
  CODIGOVENTASERVICIO DECIMAL(18) NOT NULL,
  CODIGOPRODUCTO DECIMAL(18),
  AUTORIZACION VARCHAR(50) NOT NULL,
  IDENTIFICADOR VARCHAR(50) NOT NULL,
  VALOR DECIMAL(23,9) NOT NULL,
  CODIGOPRODUCTOARCHIVO VARCHAR(20),
  FECHAVENTA TIMESTAMP,
  OBSERVACION VARCHAR(255),
  VENTAMENOSIVA DECIMAL(23,9),
  VENTAMENOSICE DECIMAL(23,9),
  IVA DECIMAL(23,9),
  ICE DECIMAL(23,9),
  COMISION DECIMAL(23,9),
  VALORBRUTO DECIMAL(23,9),
  CODIGOCOMPANIA INTEGER,
  CODIGOLOCAL INTEGER,
  CODIGOLOCALARCHIVO INTEGER,
  CODIGOCARGA DECIMAL(16),
  NUMEROCUOTA DECIMAL(3),
  ESTADOVENTA VARCHAR(3),
  TOTALAPAGAR DECIMAL(23,9),
  TOTALPAGADO DECIMAL(23,9),
  NUMEROPAGOS DECIMAL(3),
  FECHAULTIMOPAGO TIMESTAMP,
  ERRORES VARCHAR(255),
  CODIGOREGLACOMISION DECIMAL(10),
  PORCENTAJECOMISION DECIMAL(6,3),
  PORCENTAJEIVA DECIMAL(6,3),
  PORCENTAJEICE DECIMAL(6,3),
  ESTADO VARCHAR(3),
  USUARIOREGISTRO VARCHAR(32) NOT NULL,
  FECHAREGISTRO TIMESTAMP NOT NULL,
  USUARIOMODIFICACION VARCHAR(32),
  FECHAMODIFICACION TIMESTAMP,
  CODIGOPERADORARCHIVO VARCHAR(10),
  CODIGOVENTA DECIMAL(16),
  FECHAEXTEMPORANEA DATE,
  PRIMARY KEY (CODIGOVENTASERVICIO)
);

